Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2022-11, with the labels that each got.

#15 🧩 :: (#14) 기업체 등록 api 구현
  src/main/java/com/example/jobis/domain/company/controller/CompanyController.java
  src/main/java/com/example/jobis/domain/company/controller/dto/request/.gitkeep
  src/main/java/com/example/jobis/domain/company/controller/dto/request/CompanyDetailsRequest.java
  src/main/java/com/example/jobis/domain/company/controller/dto/request/RegisterCompanyRequest.java
  src/main/java/com/example/jobis/domain/company/domain/Company.java
  src/main/java/com/example/jobis/domain/company/domain/CompanyDetails.java
  src/main/java/com/example/jobis/domain/company/domain/repository/.gitkeep
  src/main/java/com/example/jobis/domain/company/domain/repository/CompanyDetailsRepository.java
  src/main/java/com/example/jobis/domain/company/domain/repository/CompanyRepository.java
  src/main/java/com/example/jobis/domain/company/domain/type/Address.java
  src/main/java/com/example/jobis/domain/company/domain/type/CompanyInfo.java
  src/main/java/com/example/jobis/domain/company/domain/type/Contact.java
  src/main/java/com/example/jobis/domain/company/domain/type/Manager.java
  src/main/java/com/example/jobis/domain/company/exception/.gitkeep
  src/main/java/com/example/jobis/domain/company/exception/InvalidBusinessNumberException.java
  src/main/java/com/example/jobis/domain/company/facade/.gitkeep
  src/main/java/com/example/jobis/domain/company/facade/CompanyFacade.java
  src/main/java/com/example/jobis/domain/company/service/.gitkeep
  src/main/java/com/example/jobis/domain/company/service/RegisterCompanyService.java
  src/main/java/com/example/jobis/infrastructure/resttemplate/dto/response/BusinessNumberResponse.java
  src/main/java/com/example/jobis/infrastructure/resttemplate/dto/response/BusinessNumberResponseBody.java
  src/main/java/com/example/jobis/infrastructure/resttemplate/dto/response/BusinessNumberResponseHeader.java
  src/main/java/com/example/jobis/infrastructure/resttemplate/dto/response/BusinessNumberResponseItem.java
  src/main/java/com/example/jobis/infrastructure/resttemplate/dto/response/BusinessNumberResponseItems.java
  src/main/java/com/example/jobis/infrastructure/resttemplate/facade/RestTemplateFacade.java
  src/main/resources/application.yml
Labels: 기능 추가

#21 🧩 :: (#18) 회사정보 입력 api
  src/main/java/com/example/jobis/domain/company/controller/CompanyController.java
  src/main/java/com/example/jobis/domain/company/controller/dto/request/CompanyDetailsRequest.java
  src/main/java/com/example/jobis/domain/company/domain/CompanyDetails.java
  src/main/java/com/example/jobis/domain/company/domain/repository/CompanyRepository.java
  src/main/java/com/example/jobis/domain/company/exception/CompanyAlreadyExistsException.java
  src/main/java/com/example/jobis/domain/company/exception/InvalidBusinessNumberException.java
  src/main/java/com/example/jobis/domain/company/facade/CompanyFacade.java
  src/main/java/com/example/jobis/domain/company/service/CreateCompanyDetailsService.java
  src/main/java/com/example/jobis/domain/company/service/RegisterCompanyService.java
  src/main/java/com/example/jobis/domain/user/controller/UserController.java
  src/main/java/com/example/jobis/domain/user/controller/dto/request/LoginRequest.java
  src/main/java/com/example/jobis/domain/user/controller/dto/response/TokenResponse.java
  src/main/java/com/example/jobis/domain/user/exception/InvalidPasswordException.java
  src/main/java/com/example/jobis/domain/user/facade/UserFacade.java
  src/main/java/com/example/jobis/domain/user/service/LoginService.java
  src/main/java/com/example/jobis/global/error/exception/ErrorCode.java
Labels: 기능 추가, 기능 수정

#26 🔗 :: (#11) 모집의뢰 도메인 작성
  src/main/java/com/example/jobis/domain/company/domain/Attachment.java
  src/main/java/com/example/jobis/domain/company/domain/Company.java
  src/main/java/com/example/jobis/domain/company/domain/CompanyDetails.java
  src/main/java/com/example/jobis/domain/recruit/domain/Recruit.java
  src/main/java/com/example/jobis/domain/recruit/domain/RecruitArea.java
  src/main/java/com/example/jobis/domain/recruit/domain/RequiredLicences.java
  src/main/java/com/example/jobis/domain/recruit/domain/TechList.java
  src/main/java/com/example/jobis/domain/recruit/domain/TechListId.java
  src/main/java/com/example/jobis/domain/recruit/domain/enums/RecruitStatus.java
  src/main/java/com/example/jobis/domain/recruit/domain/repository/.gitkeep
  src/main/java/com/example/jobis/domain/recruit/domain/repository/RecruitAreaRepository.java
  src/main/java/com/example/jobis/domain/recruit/domain/repository/RecruitRepository.java
  src/main/java/com/example/jobis/domain/recruit/domain/repository/RequiredLicencesRepository.java
  src/main/java/com/example/jobis/domain/recruit/domain/repository/TechListRepository.java
  src/main/java/com/example/jobis/domain/recruit/domain/type/Pay.java
  src/main/java/com/example/jobis/domain/recruit/domain/type/RecruitDate.java
  src/main/java/com/example/jobis/domain/user/domain/User.java
  src/main/java/com/example/jobis/global/security/SecurityConfig.java
Labels: 프로젝트 세팅

#25 🛠 :: 사업체 등록 api 리팩토링
  src/main/java/com/example/jobis/domain/company/controller/CompanyController.java
  src/main/java/com/example/jobis/domain/company/controller/dto/request/RegisterCompanyRequest.java
  src/main/java/com/example/jobis/domain/company/service/CreateCompanyDetailsService.java
  src/main/java/com/example/jobis/domain/company/service/RegisterCompanyService.java
Labels: 리팩토링

#23 🧩 :: 회사 계정 여부 확인 api
  src/main/java/com/example/jobis/domain/company/controller/CompanyController.java
  src/main/java/com/example/jobis/domain/company/controller/dto/request/ExistsCompanyRequest.java
  src/main/java/com/example/jobis/domain/company/controller/dto/response/.gitkeep
  src/main/java/com/example/jobis/domain/company/controller/dto/response/ExistsCompanyResponse.java
  src/main/java/com/example/jobis/domain/company/service/ExistsCompanyService.java
  src/main/java/com/example/jobis/domain/user/controller/dto/request/LoginRequest.java
Labels: 기능 추가

#33 ⚙️ :: (#31) 회원가입 버그 수정
  src/main/java/com/example/jobis/domain/company/service/RegisterCompanyService.java
Labels: 버그 수정

#32 ⚙️ :: (#30) 로그인 버그 수정
  src/main/java/com/example/jobis/domain/user/controller/UserController.java
  src/main/java/com/example/jobis/global/security/SecurityConfig.java
Labels: 버그 수정

#36 🔗 :: (#35)코드 테이블
  src/main/java/com/example/jobis/domain/code/domain/Code.java
  src/main/java/com/example/jobis/domain/code/domain/enums/CodeType.java
  src/main/java/com/example/jobis/domain/code/domain/repository/CodeRepository.java
  src/main/java/com/example/jobis/domain/code/presentaion/CodeController.java
  src/main/java/com/example/jobis/domain/code/presentaion/dto/response/CodeResponse.java
  src/main/java/com/example/jobis/domain/code/service/FindCodeService.java
  src/main/java/com/example/jobis/domain/company/controller/CompanyController.java
  src/main/java/com/example/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#41 🗂 :: (#38) 학생 엔티티 추가
  src/main/java/com/example/jobis/domain/student/domain/Portfolio.java
  src/main/java/com/example/jobis/domain/student/domain/Student.java
  src/main/java/com/example/jobis/domain/student/domain/types/Gender.java
  src/main/java/com/example/jobis/domain/student/domain/types/Grade.java
Labels: 프로젝트 세팅
