Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2023-09, with the labels that each got.

#404 🔗 :: (#403) slack webhook 연동 기능 추가
  jobis-application/src/main/java/team/retum/jobis/common/spi/SendEmailPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/auth/usecase/SendAuthCodeUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/bug/model/BugReport.java
  jobis-application/src/main/java/team/retum/jobis/domain/bug/spi/PublishBugReportEventPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/bug/usecase/CreateBugReportUseCase.java
  jobis-infrastructure/build.gradle
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/bug/persistence/entity/BugReportEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/bug/persistence/mapper/BugReportMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/bug/BugReportHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/bug/BugReportPublisher.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/bug/model/BugReportEvent.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/exception/ExceptionEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/exception/model/ExceptionEvent.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/notification/NotificationEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/error/GlobalExceptionFilter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/FilterConfig.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
  jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/ses/SendEmailAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/webhook/WebhookUtil.java
  jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/webhook/slack/SlackAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/webhook/slack/SlackConfig.java
  jobis-infrastructure/src/main/resources/application.yml
Labels: 기능 추가

#410 🔗 :: (#409) 취업 관리 페이지 회사 조회 페이지네이션 추가
  jobis-application/src/main/java/team/retum/jobis/common/util/NumberUtil.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/TeacherQueryApplicationsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/CompanyFilter.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/TeacherQueryEmployCompaniesResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/QueryCompanyPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/StudentQueryCompaniesUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/TeacherQueryCompaniesUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/TeacherQueryEmployCompaniesUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/RecruitmentFilter.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/StudentQueryRecruitmentsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
Labels: 기능 수정

#415 🔗 :: (#414) CurrentUserHolder리펙토링
  jobis-infrastructure/src/main/java/team/retum/jobis/global/aop/ThreadLocalAspect.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/error/GlobalExceptionFilter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/CurrentUserHolder.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/company/CompanyDetailsService.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/student/StudentDetailsService.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/teacher/TeacherDetailsService.java
Labels: 리팩토링

#407 🔗 :: (#406) 이미지가 없을 때 슬랙 버그 내용이 안뜨는 문제 해결
  jobis-application/src/main/java/team/retum/jobis/domain/bug/model/BugReport.java
  jobis-application/src/main/java/team/retum/jobis/domain/bug/spi/PublishBugReportEventPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/bug/usecase/CreateBugReportUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/bug/BugReportHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/bug/PublishBugReportEventAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/bug/model/BugReportEvent.java
  jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/webhook/WebhookUtil.java
  jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/webhook/slack/SlackAdapter.java
Labels: 기능 수정

#416 🔗 :: (#413) 애그거트 정리
  jobis-application/src/main/java/team/retum/jobis/domain/application/model/Application.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/model/ApplicationAttachment.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/spi/CommandApplicationPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/ChangeApplicationsStatusUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/CreateApplicationUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/RejectApplicationUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/model/Company.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/model/CompanyAttachment.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/CommandCompanyPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/QueryCompanyPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/vo/CompanyDetailsVO.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/QueryCompanyDetailsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/RegisterCompanyUseCase.java
  jobis-application/src/main/resources/application.properties
  jobis-infrastructure/build.gradle
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/entity/ApplicationAttachmentEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/entity/ApplicationEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/mapper/ApplicationAttachmentMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/mapper/ApplicationMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/repository/ApplicationAttachmentJpaRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/repository/ApplicationJpaRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyAttachmentEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/mapper/CompanyAttachmentMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/mapper/CompanyMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/repository/CompanyAttachmentJpaRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/repository/vo/QueryCompanyDetailsVO.java
  jobis-infrastructure/src/main/resources/application.yml
Labels: 리팩토링

#420 🔗 :: (#419) 같은 모집의뢰 동시지원 방지
  jobis-application/src/main/java/team/retum/jobis/domain/application/model/ApplicationAttachment.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/model/ApplicationStatus.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/spi/CommandApplicationPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/spi/QueryApplicationPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/ChangeApplicationsStatusUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/CreateApplicationUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/repository/ApplicationJpaRepository.java
Labels: 리팩토링, 버그 수정

#423 🔗 :: (#422) BugReport 에그리거트 정리
  jobis-application/src/main/java/team/retum/jobis/domain/bug/model/BugAttachment.java
  jobis-application/src/main/java/team/retum/jobis/domain/bug/model/BugReport.java
  jobis-application/src/main/java/team/retum/jobis/domain/bug/spi/CommandBugReportPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/bug/usecase/CreateBugReportUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/bug/usecase/QueryBugReportDetailsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/bug/persistence/BugReportPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/bug/persistence/entity/BugAttachmentEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/bug/persistence/entity/BugAttachmentId.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/bug/persistence/entity/BugReportEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/bug/persistence/mapper/BugAttachmentMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/bug/persistence/mapper/BugReportMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/bug/persistence/repository/BugAttachmentJpaRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/error/GlobalExceptionFilter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/util/LogUtil.java
  jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/webhook/slack/SlackAdapter.java
  jobis-infrastructure/src/main/resources/application.yml
Labels: 리팩토링

#426 🔗 :: (#421) 페이지 개수 조회 api
  jobis-application/src/main/java/team/retum/jobis/common/dto/response/TotalPageCountResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/TeacherQueryCompaniesResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/StudentQueryCompaniesUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/TeacherQueryCompaniesUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/TeacherQueryRecruitmentsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/StudentQueryRecruitmentsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
Labels: 기능 추가
