Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2023-02, with the labels that each got.

#100 🗂️ :: (#98) 기업 지원서 엔티티 생성
  gradlew
  src/main/java/com/example/jobis/domain/application/controller/.gitkeep
  src/main/java/com/example/jobis/domain/application/domain/Application.java
  src/main/java/com/example/jobis/domain/application/domain/ApplicationAttachment.java
  src/main/java/com/example/jobis/domain/application/exception/.gitkeep
  src/main/java/com/example/jobis/domain/application/facade/.gitkeep
  src/main/java/com/example/jobis/domain/application/service/.gitkeep
  src/main/java/com/example/jobis/domain/company/domain/Company.java
  src/main/java/com/example/jobis/domain/company/domain/CompanyAttachment.java
  src/main/java/com/example/jobis/domain/company/domain/repository/AttachmentRepository.java
  src/main/java/com/example/jobis/domain/company/domain/repository/CompanyAttachmentRepository.java
  src/main/java/com/example/jobis/domain/student/controller/dto/request/StudentSignUpRequest.java
  src/main/java/com/example/jobis/domain/student/domain/Student.java
  src/main/java/com/example/jobis/domain/student/service/StudentSignUpService.java
Labels: 프로젝트 세팅

#104 🧩 :: (#101) 기업 지원 api 추가
  src/main/java/com/example/jobis/domain/application/controller/.gitkeep
  src/main/java/com/example/jobis/domain/application/controller/ApplicationController.java
  src/main/java/com/example/jobis/domain/application/controller/dto/request/CreateApplicationRequest.java
  src/main/java/com/example/jobis/domain/application/domain/Application.java
  src/main/java/com/example/jobis/domain/application/domain/enums/ApplicationStatus.java
  src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationAttachmentJpaRepository.java
  src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationJpaRepository.java
  src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/com/example/jobis/domain/application/exception/.gitkeep
  src/main/java/com/example/jobis/domain/application/exception/ApplicationAlreadyExistsException.java
  src/main/java/com/example/jobis/domain/application/service/.gitkeep
  src/main/java/com/example/jobis/domain/application/service/CreateApplicationService.java
  src/main/java/com/example/jobis/domain/student/facade/StudentFacade.java
  src/main/java/com/example/jobis/global/error/exception/ErrorCode.java
  src/main/java/com/example/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#108 🧩 :: (#106) 기업 지원 내역 api
  src/main/java/com/example/jobis/domain/application/controller/dto/response/StudentApplicationListResponse.java
  src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/com/example/jobis/domain/application/service/QueryStudentApplicationService.java
  src/main/java/com/example/jobis/domain/student/controller/StudentController.java
  src/main/java/com/example/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#110 🛠️ :: (#109) 지원서 관련 리팩토링
  src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationJpaRepository.java
  src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/com/example/jobis/domain/application/exception/ApplicationNotFoundException.java
  src/main/java/com/example/jobis/domain/application/exception/InvalidGradeException.java
  src/main/java/com/example/jobis/domain/application/service/CreateApplicationService.java
  src/main/java/com/example/jobis/global/error/exception/ErrorCode.java
Labels: 리팩토링

#118 🧩 :: (#) 지원서 삭제 api 추가
  src/main/java/com/example/jobis/domain/application/controller/ApplicationController.java
  src/main/java/com/example/jobis/domain/application/controller/dto/response/StudentApplicationListResponse.java
  src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationJpaRepository.java
  src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/com/example/jobis/domain/application/exception/InvalidStudentException.java
  src/main/java/com/example/jobis/domain/application/service/DeleteApplicationService.java
  src/main/java/com/example/jobis/global/error/exception/ErrorCode.java
  src/main/java/com/example/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#72 🧩 :: (#62) 모집의뢰서 상세조회 api
  src/main/java/com/example/jobis/domain/code/facade/CodeFacade.java
  src/main/java/com/example/jobis/domain/recruit/controller/dto/response/StudentRecruitDetailsResponse.java
  src/main/java/com/example/jobis/domain/recruit/domain/repository/vo/QueryRecruitmentListVO.java
  src/main/java/com/example/jobis/domain/recruit/service/QueryStudentRecruitDetailsService.java
  src/main/java/com/example/jobis/domain/student/controller/StudentController.java
Labels: 기능 추가, 리팩토링, 버그 수정

#123 🛠️ :: (#120) 지원서 리팩토링
  src/main/java/com/example/jobis/domain/application/controller/ApplicationController.java
  src/main/java/com/example/jobis/domain/application/domain/Application.java
  src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationJpaRepository.java
  src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/com/example/jobis/domain/application/service/CreateApplicationService.java
  src/main/java/com/example/jobis/domain/recruit/domain/repository/RecruitmentRepository.java
Labels: 리팩토링

#122 🔗 :: (#121)코드 조회 리펙토링
  src/main/java/com/example/jobis/domain/code/controller/CodeController.java
  src/main/java/com/example/jobis/domain/code/domain/repository/CodeRepository.java
  src/main/java/com/example/jobis/domain/code/service/FindCodeService.java
  src/main/java/com/example/jobis/global/security/jwt/JwtTokenProvider.java
Labels: 리팩토링
