Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2023-12, with the labels that each got.

#488 🔗 :: (#487) 선생님 지원서 리스트 조회 페이징
  jobis-application/src/main/java/team/retum/jobis/domain/application/spi/QueryApplicationPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/CompanyQueryApplicationsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryMyApplicationsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/TeacherQueryApplicationsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java
Labels: 기능 수정

#490 🔗 :: (#489) 지원한 학생수 버그
  jobis-application/src/main/java/team/retum/jobis/domain/application/dto/response/QueryEmploymentCountResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/spi/QueryApplicationPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryEmploymentCountUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/student/spi/QueryStudentPort.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/StudentPersistenceAdapter.java
Labels: 버그 수정

#498 🔗 :: (#497) CurrentUser 리펙토링
  .github/CODEOWNERS
  jobis-infrastructure/src/main/java/team/retum/jobis/global/error/GlobalExceptionFilter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/CurrentUserHolder.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/company/CompanyDetails.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/company/CompanyDetailsService.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/student/StudentDetails.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/student/StudentDetailsService.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/teacher/TeacherDetails.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/teacher/TeacherDetailsService.java
Labels: 리팩토링
