Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2023-01, with the labels that each got.

#71 🧩 :: (#61) 회사 상세정보 조회 api
  src/main/java/com/example/jobis/domain/company/controller/CompanyController.java
  src/main/java/com/example/jobis/domain/company/controller/dto/response/CompanyDetailsResponse.java
  src/main/java/com/example/jobis/domain/company/facade/CompanyFacade.java
  src/main/java/com/example/jobis/domain/company/service/QueryCompanyDetailsService.java
  src/main/java/com/example/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#80 ⚙️ :: 존재하지 않는 사업자번호로 조회시 500 해결
  src/main/java/com/example/jobis/domain/company/facade/CompanyFacade.java
Labels: 버그 수정

#77 🛩️ :: (#76) 회사 비밀번호 정규표현식 수정
  src/main/java/com/example/jobis/domain/company/controller/dto/request/RegisterCompanyRequest.java
Labels: 기능 수정

#70 🧩 :: (#60) 모집 의뢰서 리스트 조회 api
  src/main/java/com/example/jobis/domain/code/controller/dto/response/CodeResponse.java
  src/main/java/com/example/jobis/domain/code/domain/Code.java
  src/main/java/com/example/jobis/domain/code/domain/repository/RecruitAreaCodeRepository.java
  src/main/java/com/example/jobis/domain/code/exception/CodeNotFoundException.java
  src/main/java/com/example/jobis/domain/code/exception/RecruitAreaCodeNotFoundException.java
  src/main/java/com/example/jobis/domain/code/facade/CodeFacade.java
  src/main/java/com/example/jobis/domain/company/controller/dto/request/CompanyDetailsRequest.java
  src/main/java/com/example/jobis/domain/recruit/controller/RecruitController.java
  src/main/java/com/example/jobis/domain/recruit/controller/dto/response/.gitkeep
  src/main/java/com/example/jobis/domain/recruit/controller/dto/response/RecruitListResponse.java
  src/main/java/com/example/jobis/domain/recruit/domain/repository/RecruitAreaRepository.java
  src/main/java/com/example/jobis/domain/recruit/exception/.gitkeep
  src/main/java/com/example/jobis/domain/recruit/exception/RecruitAreaNotFoundException.java
  src/main/java/com/example/jobis/domain/recruit/service/QueryRecruitListService.java
  src/main/java/com/example/jobis/domain/student/controller/StudentController.java
  src/main/java/com/example/jobis/global/error/exception/ErrorCode.java
  src/main/java/com/example/jobis/global/security/SecurityConfig.java
Labels: 기능 추가, 리팩토링

#81 🔗 :: (#78)NPE해결
  src/main/java/com/example/jobis/domain/recruit/controller/dto/request/ApplyRecruitmentRequest.java
  src/main/java/com/example/jobis/domain/recruit/domain/Recruit.java
  src/main/java/com/example/jobis/domain/recruit/service/ApplyRecruitmentService.java
Labels: 리팩토링, 버그 수정
