Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2023-05, with the labels that each got.

#236 🔗 :: (#235) 학생인증 api
  src/main/java/team/returm/jobis/domain/student/domain/repository/VerifiedStudentJpaRepository.java
  src/main/java/team/returm/jobis/domain/student/domain/repository/VerifiedStudentRepository.java
  src/main/java/team/returm/jobis/domain/student/presentation/StudentController.java
  src/main/java/team/returm/jobis/domain/student/service/VerifyStudentService.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#238 🔗 :: (#237) 북마크 관련 api
  src/main/java/team/returm/jobis/domain/bookmark/domain/Bookmark.java
  src/main/java/team/returm/jobis/domain/bookmark/domain/BookmarkId.java
  src/main/java/team/returm/jobis/domain/bookmark/domain/repository/BookmarkJpaRepository.java
  src/main/java/team/returm/jobis/domain/bookmark/domain/repository/BookmarkRepository.java
  src/main/java/team/returm/jobis/domain/bookmark/domain/repository/vo/QueryStudentBookmarksVO.java
  src/main/java/team/returm/jobis/domain/bookmark/exception/.gitkeep
  src/main/java/team/returm/jobis/domain/bookmark/exception/BookmarkNotFoundException.java
  src/main/java/team/returm/jobis/domain/bookmark/presentation/.gitkeep
  src/main/java/team/returm/jobis/domain/bookmark/presentation/BookmarkController.java
  src/main/java/team/returm/jobis/domain/bookmark/presentation/dto/response/QueryStudentBookmarksResponse.java
  src/main/java/team/returm/jobis/domain/bookmark/service/.gitkeep
  src/main/java/team/returm/jobis/domain/bookmark/service/CreateBookmarkService.java
  src/main/java/team/returm/jobis/domain/bookmark/service/DeleteBookmarkService.java
  src/main/java/team/returm/jobis/domain/bookmark/service/QueryStudentBookmarksService.java
  src/main/java/team/returm/jobis/global/error/exception/ErrorCode.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#232 🔗 :: (#230) 학생 메인페이지 api
  src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/team/returm/jobis/domain/application/domain/repository/vo/QueryApplyCompaniesVO.java
  src/main/java/team/returm/jobis/domain/application/domain/repository/vo/QueryTotalApplicationCountVO.java
  src/main/java/team/returm/jobis/domain/student/domain/Student.java
  src/main/java/team/returm/jobis/domain/student/domain/repository/StudentRepository.java
  src/main/java/team/returm/jobis/domain/student/presentation/StudentController.java
  src/main/java/team/returm/jobis/domain/student/presentation/dto/response/StudentMainPageResponse.java
  src/main/java/team/returm/jobis/domain/student/service/StudentMainPageService.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#249 🔗 :: (#247) 학생 존재 여부 인증 회원가입시 정보 삭제하게 변경
  src/main/java/team/returm/jobis/domain/student/domain/repository/VerifiedStudentJpaRepository.java
  src/main/java/team/returm/jobis/domain/student/domain/repository/VerifiedStudentRepository.java
  src/main/java/team/returm/jobis/domain/student/service/StudentSignUpService.java
  src/main/java/team/returm/jobis/domain/student/service/VerifyStudentService.java
Labels: 기능 수정

#253 🔗 :: (#251) 이메일 템플릿 수정
  src/main/resources/templates/signup-template.html
Labels: 기능 수정

#255 🔗 :: (#254) 코드조회 API 병합
  .github/ISSUE_TEMPLATE/bug.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/CI.yml
  .github/workflows/build.yml
  src/main/java/team/returm/jobis/domain/code/domain/RecruitAreaCode.java
  src/main/java/team/returm/jobis/domain/code/domain/repository/CodeRepository.java
  src/main/java/team/returm/jobis/domain/code/facade/CodeFacade.java
  src/main/java/team/returm/jobis/domain/code/presentation/CodeController.java
  src/main/java/team/returm/jobis/domain/code/presentation/dto/response/CodesResponse.java
  src/main/java/team/returm/jobis/domain/code/presentation/dto/response/JobCodesResponse.java
  src/main/java/team/returm/jobis/domain/code/service/QueryBusinessAreaCodesService.java
  src/main/java/team/returm/jobis/domain/code/service/QueryCodesService.java
  src/main/java/team/returm/jobis/domain/code/service/QueryJobCodesService.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
Labels: 리팩토링

#260 🔗 :: (#259) 선생님 모집의뢰서 조회 버그
  src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
Labels: 버그 수정

#245 🔗 :: (#243) 후기 생성/제거 api
  src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationJpaRepository.java
  src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/team/returm/jobis/domain/recruitment/domain/RecruitArea.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/request/ApplyRecruitmentRequest.java
  src/main/java/team/returm/jobis/domain/review/domain/QnAElement.java
  src/main/java/team/returm/jobis/domain/review/domain/Review.java
  src/main/java/team/returm/jobis/domain/review/exception/.gitkeep
  src/main/java/team/returm/jobis/domain/review/exception/ReviewCannotWriteException.java
  src/main/java/team/returm/jobis/domain/review/exception/ReviewNotFoundException.java
  src/main/java/team/returm/jobis/domain/review/presentation/.gitkeep
  src/main/java/team/returm/jobis/domain/review/presentation/ReviewController.java
  src/main/java/team/returm/jobis/domain/review/presentation/dto/CreateReviewRequest.java
  src/main/java/team/returm/jobis/domain/review/service/.review
  src/main/java/team/returm/jobis/domain/review/service/CreateReviewService.java
  src/main/java/team/returm/jobis/domain/review/service/DeleteReviewService.java
  src/main/java/team/returm/jobis/global/config/MongoConfig.java
  src/main/java/team/returm/jobis/global/error/exception/ErrorCode.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#263 🔗 :: (#261) ses 적용
  build.gradle
  src/main/java/team/returm/jobis/domain/auth/service/SendAuthCodeService.java
  src/main/java/team/returm/jobis/global/util/jms/JmsProperties.java
  src/main/java/team/returm/jobis/global/util/jms/JmsUtil.java
  src/main/java/team/returm/jobis/infrastructure/feignClients/dto/BusinessNumberResponse.java
  src/main/java/team/returm/jobis/infrastructure/s3/S3Util.java
  src/main/java/team/returm/jobis/infrastructure/ses/AwsSesConfig.java
  src/main/java/team/returm/jobis/infrastructure/ses/AwsSesProperties.java
  src/main/java/team/returm/jobis/infrastructure/ses/SesUtil.java
  src/main/resources/application.yml
Labels: 기능 추가, 리팩토링

#256 🔗 :: (#246) 후기 조회 api
  src/main/java/team/returm/jobis/domain/code/domain/repository/CodeRepository.java
  src/main/java/team/returm/jobis/domain/company/domain/repository/CompanyJpaRepository.java
  src/main/java/team/returm/jobis/domain/company/domain/repository/CompanyRepository.java
  src/main/java/team/returm/jobis/domain/company/service/TeacherQueryCompaniesService.java
  src/main/java/team/returm/jobis/domain/review/domain/repository/ReviewRepository.java
  src/main/java/team/returm/jobis/domain/review/presentation/ReviewController.java
  src/main/java/team/returm/jobis/domain/review/presentation/dto/QueryReviewDetailResponse.java
  src/main/java/team/returm/jobis/domain/review/presentation/dto/QueryReviewsResponse.java
  src/main/java/team/returm/jobis/domain/review/service/QueryReviewDetailService.java
  src/main/java/team/returm/jobis/domain/review/service/QueryReviewsService.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#269 🔗 :: (#268) 선생님 모집의뢰 상세 조회
  src/main/java/team/returm/jobis/domain/recruitment/presentation/RecruitmentController.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/response/QueryRecruitmentDetailResponse.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/response/RecruitAreaResponse.java
  src/main/java/team/returm/jobis/domain/recruitment/service/QueryRecruitmentDetailService.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#266 🔗 :: (#265) 중복 예외처리
  src/main/java/team/returm/jobis/domain/review/domain/repository/ReviewRepository.java
  src/main/java/team/returm/jobis/domain/review/exception/ReviewAlreadyExistsException.java
  src/main/java/team/returm/jobis/domain/review/exception/error/ReviewErrorCode.java
  src/main/java/team/returm/jobis/domain/review/service/CreateReviewService.java
Labels: 기능 추가

#271 🔗 :: (#225) 페이지 총 개수 반환
  src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/team/returm/jobis/domain/application/presentation/dto/response/TeacherQueryApplicationsResponse.java
  src/main/java/team/returm/jobis/domain/application/service/TeacherQueryApplicationsService.java
  src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
  src/main/java/team/returm/jobis/domain/recruitment/domain/type/RecruitDate.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/RecruitmentController.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/RecruitmentFilter.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/response/TeacherQueryRecruitmentsResponse.java
  src/main/java/team/returm/jobis/domain/recruitment/service/StudentQueryRecruitmentsService.java
  src/main/java/team/returm/jobis/domain/recruitment/service/TeacherQueryRecruitmentsService.java
Labels: 기능 추가, 리팩토링

#274 🔗 :: (#272) parent code로 조회 필터 추가
  src/main/java/team/returm/jobis/domain/code/domain/repository/CodeRepository.java
  src/main/java/team/returm/jobis/domain/code/presentation/CodeController.java
  src/main/java/team/returm/jobis/domain/code/presentation/dto/response/CodesResponse.java
  src/main/java/team/returm/jobis/domain/code/service/QueryCodesService.java
  src/main/java/team/returm/jobis/global/util/StringUtil.java
Labels: 기능 추가

#277 🔗 :: (#276) 프로필 이미지 추가
  src/main/java/team/returm/jobis/domain/company/domain/Company.java
  src/main/java/team/returm/jobis/domain/company/domain/repository/CompanyRepository.java
  src/main/java/team/returm/jobis/domain/company/domain/repository/vo/QueryCompanyDetailsVO.java
  src/main/java/team/returm/jobis/domain/company/domain/repository/vo/StudentQueryCompaniesVO.java
  src/main/java/team/returm/jobis/domain/company/domain/repository/vo/TeacherQueryCompaniesVO.java
  src/main/java/team/returm/jobis/domain/company/presentation/dto/request/RegisterCompanyRequest.java
  src/main/java/team/returm/jobis/domain/company/presentation/dto/request/UpdateCompanyDetailsRequest.java
  src/main/java/team/returm/jobis/domain/company/presentation/dto/response/CompanyMyPageResponse.java
  src/main/java/team/returm/jobis/domain/company/presentation/dto/response/QueryCompanyDetailsResponse.java
  src/main/java/team/returm/jobis/domain/company/presentation/dto/response/TeacherQueryCompaniesResponse.java
  src/main/java/team/returm/jobis/domain/company/service/CompanyMyPageService.java
  src/main/java/team/returm/jobis/domain/company/service/RegisterCompanyService.java
  src/main/java/team/returm/jobis/domain/company/service/TeacherQueryCompaniesService.java
  src/main/java/team/returm/jobis/domain/student/domain/Student.java
  src/main/java/team/returm/jobis/domain/student/presentation/dto/request/StudentSignUpRequest.java
  src/main/java/team/returm/jobis/domain/student/presentation/dto/response/StudentMyPageResponse.java
  src/main/java/team/returm/jobis/domain/student/service/StudentSignUpService.java
  src/main/java/team/returm/jobis/global/util/ImageProperty.java
Labels: 기능 추가

#280 🔗 :: (#279) 페이징 버그
  src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
  src/main/java/team/returm/jobis/domain/recruitment/domain/repository/vo/QueryRecruitmentsVO.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/RecruitmentFilter.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/response/StudentQueryRecruitmentsResponse.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/response/TeacherQueryRecruitmentsResponse.java
  src/main/java/team/returm/jobis/domain/recruitment/service/StudentQueryRecruitmentsService.java
  src/main/java/team/returm/jobis/domain/recruitment/service/TeacherQueryRecruitmentsService.java
  src/main/java/team/returm/jobis/global/config/MysqlDialectConfig.java
  src/main/resources/application.yml
Labels: 버그 수정

#284 🔗 :: (#283) lint
  src/main/java/team/returm/jobis/domain/application/service/TeacherQueryApplicationsService.java
  src/main/java/team/returm/jobis/domain/bookmark/service/BookmarkService.java
  src/main/java/team/returm/jobis/domain/code/presentation/dto/response/CodesResponse.java
  src/main/java/team/returm/jobis/domain/code/service/QueryCodesService.java
  src/main/java/team/returm/jobis/domain/company/service/TeacherQueryCompaniesService.java
  src/main/java/team/returm/jobis/domain/recruitment/domain/type/RecruitDate.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/RecruitmentController.java
  src/main/java/team/returm/jobis/domain/review/domain/Review.java
  src/main/java/team/returm/jobis/domain/review/service/CreateReviewService.java
  src/main/java/team/returm/jobis/domain/student/presentation/StudentController.java
  src/main/java/team/returm/jobis/domain/student/service/StudentMyPageService.java
  src/main/java/team/returm/jobis/global/error/ErrorProperty.java
  src/main/java/team/returm/jobis/global/exception/ExpiredTokenException.java
Labels: 리팩토링

#288 🔗 :: (#287) 기업조회 총 페이지 개수 반환
  src/main/java/team/returm/jobis/domain/company/domain/repository/CompanyRepository.java
  src/main/java/team/returm/jobis/domain/company/domain/repository/vo/TeacherQueryCompaniesVO.java
  src/main/java/team/returm/jobis/domain/company/presentation/CompanyController.java
  src/main/java/team/returm/jobis/domain/company/presentation/dto/CompanyFilter.java
  src/main/java/team/returm/jobis/domain/company/presentation/dto/response/TeacherQueryCompaniesResponse.java
  src/main/java/team/returm/jobis/domain/company/service/StudentQueryCompaniesService.java
  src/main/java/team/returm/jobis/domain/company/service/TeacherQueryCompaniesService.java
  src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
Labels: 기능 추가

#293 🔗 :: (#292) 파일 다중 업로드
  src/main/java/team/returm/jobis/domain/file/exception/FileUploadFailedException.java
  src/main/java/team/returm/jobis/domain/file/exception/error/FileErrorCode.java
  src/main/java/team/returm/jobis/domain/file/presentation/FileController.java
  src/main/java/team/returm/jobis/domain/file/presentation/dto/response/FileUploadResponse.java
  src/main/java/team/returm/jobis/domain/file/service/FileUploadService.java
  src/main/java/team/returm/jobis/global/config/AsyncConfig.java
  src/main/java/team/returm/jobis/infrastructure/s3/S3Util.java
  src/main/resources/application.yml
Labels: 기능 추가, 리팩토링

#286 🔗 :: (#285) review created_date 제거
  src/main/java/team/returm/jobis/domain/application/domain/Application.java
  src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationJpaRepository.java
  src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/team/returm/jobis/domain/review/presentation/dto/QueryReviewDetailResponse.java
  src/main/java/team/returm/jobis/domain/review/presentation/dto/QueryReviewsResponse.java
  src/main/java/team/returm/jobis/domain/review/service/CreateReviewService.java
  src/main/java/team/returm/jobis/domain/review/service/QueryReviewDetailService.java
  src/main/java/team/returm/jobis/domain/review/service/QueryReviewsService.java
Labels: 기능 수정
