Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2023-07, with the labels that each got.

#356 🔗 :: (#355) 기업 지원자 조회 할 때 지원자 프로필 추가
  src/main/java/team/retum/jobis/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/team/retum/jobis/domain/application/domain/repository/vo/QueryApplicationVO.java
  src/main/java/team/retum/jobis/domain/application/presentation/dto/response/CompanyQueryApplicationsResponse.java
  src/main/java/team/retum/jobis/domain/application/service/QueryCompanyApplicationsService.java
Labels: 기능 수정

#352 🔗 :: (334) 지원서 파일 구분
  src/main/java/team/retum/jobis/domain/application/domain/ApplicationAttachment.java
  src/main/java/team/retum/jobis/domain/application/domain/enums/AttachmentType.java
  src/main/java/team/retum/jobis/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/team/retum/jobis/domain/application/domain/repository/vo/QueryApplicationVO.java
  src/main/java/team/retum/jobis/domain/application/presentation/dto/request/CreateApplicationRequest.java
  src/main/java/team/retum/jobis/domain/application/presentation/dto/response/AttachmentResponse.java
  src/main/java/team/retum/jobis/domain/application/presentation/dto/response/CompanyQueryApplicationsResponse.java
  src/main/java/team/retum/jobis/domain/application/presentation/dto/response/StudentQueryApplicationsResponse.java
  src/main/java/team/retum/jobis/domain/application/presentation/dto/response/TeacherQueryApplicationsResponse.java
  src/main/java/team/retum/jobis/domain/application/service/ChangeFieldTrainDateService.java
  src/main/java/team/retum/jobis/domain/application/service/CreateApplicationService.java
  src/main/java/team/retum/jobis/domain/application/service/QueryCompanyApplicationsService.java
  src/main/java/team/retum/jobis/domain/application/service/QueryStudentApplicationsService.java
  src/main/java/team/retum/jobis/domain/application/service/TeacherQueryApplicationsService.java
  src/main/java/team/retum/jobis/domain/bug/domain/BugReport.java
  src/main/java/team/retum/jobis/domain/bug/presentation/dto/request/CreateBugReportRequest.java
  src/main/java/team/retum/jobis/domain/company/service/RegisterCompanyService.java
  src/main/java/team/retum/jobis/domain/file/service/FileUploadService.java
  src/main/java/team/retum/jobis/domain/recruitment/domain/Recruitment.java
  src/main/java/team/retum/jobis/domain/student/domain/Student.java
  src/main/java/team/retum/jobis/domain/student/presentation/StudentController.java
Labels: 기능 수정

#359 🔗 :: (#358) CORS 설정
  src/main/java/team/retum/jobis/global/web/WebSecurityConfig.java
Labels: 프로젝트 세팅

#357 🔗 :: (#339)[BAC-413] 모집분야 삭제시 모집분야 개수 확인
  src/main/java/team/retum/jobis/domain/recruitment/exception/error/RecruitmentErrorCode.java
  src/main/java/team/retum/jobis/domain/recruitment/service/DeleteRecruitAreaService.java
  src/main/java/team/retum/jobis/domain/recruitment/service/RecruitAreaCannotDeleteException.java
  src/main/java/team/retum/jobis/global/security/SecurityConfig.java
Labels: 기능 수정

#364 🔗 :: (#363) 개발 분야가 ALL일 때 전체 다 불러오도록 수정
  src/main/java/team/retum/jobis/domain/bug/domain/repository/BugReportRepository.java
Labels: 버그 수정
