Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2023-06, with the labels that each got.

#310 🔗 :: (#309) 콤마 리스트 구분
  src/main/java/team/returm/jobis/domain/recruitment/presentation/RecruitmentController.java
  src/main/java/team/returm/jobis/global/util/StringUtil.java
Labels: 기능 수정

#307 🔗 :: (#306) 상세주소분리
  src/main/java/team/returm/jobis/domain/company/domain/Company.java
  src/main/java/team/returm/jobis/domain/company/domain/CompanyAttachment.java
  src/main/java/team/returm/jobis/domain/company/domain/repository/CompanyRepository.java
  src/main/java/team/returm/jobis/domain/company/presentation/dto/request/RegisterCompanyRequest.java
  src/main/java/team/returm/jobis/domain/company/service/RegisterCompanyService.java
  src/main/java/team/returm/jobis/global/util/StringUtil.java
Labels: 리팩토링

#317 🔗 :: (#316) 학생 프로필사진 변경 api
  src/main/java/team/returm/jobis/domain/student/domain/Student.java
  src/main/java/team/returm/jobis/domain/student/presentation/StudentController.java
  src/main/java/team/returm/jobis/domain/student/presentation/dto/request/UpdateStudentProfileRequest.java
  src/main/java/team/returm/jobis/domain/student/service/UpdateStudentProfileService.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#331 🔗 :: (#330) 승인된 모집의뢰서만 스케줄링
  src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
  src/main/java/team/returm/jobis/domain/recruitment/service/ChangeRecruitmentStatusSchedulerService.java
Labels: 리팩토링

#337 🔗 :: (#336) APPROVED, FIELD_TRAIN, PASS는 지원 요청 불가
  src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationJpaRepository.java
  src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/team/returm/jobis/domain/application/service/CreateApplicationService.java
Labels: 기능 수정

#338 🔗 :: (#332) 모집의뢰서가 진행중일때 다른 모집의뢰서를 생성하지 못하게 함
  src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentJpaRepository.java
  src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
  src/main/java/team/returm/jobis/domain/recruitment/exception/RecruitmentAlreadyExistsException.java
  src/main/java/team/returm/jobis/domain/recruitment/exception/error/RecruitmentErrorCode.java
  src/main/java/team/returm/jobis/domain/recruitment/service/ApplyRecruitmentService.java
Labels: 기능 추가

#341 🔗 :: (#340) 500 에러 해결
  src/main/java/team/returm/jobis/domain/application/service/QueryCompanyApplicationsService.java
  src/main/java/team/returm/jobis/domain/company/service/TeacherQueryCompaniesService.java
  src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
  src/main/java/team/returm/jobis/domain/recruitment/service/QueryMyRecruitmentService.java
  src/main/java/team/returm/jobis/domain/user/presentation/UserController.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
Labels: 버그 수정

#347 🔗 :: (#346) 버그 제보 api
  src/main/java/team/returm/jobis/domain/bug/domain/repository/.gitkeep
  src/main/java/team/returm/jobis/domain/bug/domain/repository/BugAttachmentRepository.java
  src/main/java/team/returm/jobis/domain/bug/domain/repository/BugReportJpaRepository.java
  src/main/java/team/returm/jobis/domain/bug/domain/repository/BugRepository.java
  src/main/java/team/returm/jobis/domain/bug/presentation/BugController.java
  src/main/java/team/returm/jobis/domain/bug/presentation/dto/request/.gitkeep
  src/main/java/team/returm/jobis/domain/bug/presentation/dto/request/CreateBugReportRequest.java
  src/main/java/team/returm/jobis/domain/bug/service/.gitkeep
  src/main/java/team/returm/jobis/domain/bug/service/CreateBugReportService.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#354 ⚒️ :: (#353) 지원요청 가능여부 도메인 로직추가
  src/main/java/team/retum/jobis/domain/application/service/CreateApplicationService.java
  src/main/java/team/retum/jobis/domain/recruitment/domain/Recruitment.java
  src/main/java/team/retum/jobis/domain/recruitment/exception/InvalidRecruitmentStatusException.java
  src/main/java/team/retum/jobis/domain/recruitment/exception/error/RecruitmentErrorCode.java
Labels: 기능 수정
