Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2023-11, with the labels that each got.

#447 🔗 :: (#444) 코드 사용여부 추가
  jobis-application/src/main/java/team/retum/jobis/domain/code/model/Code.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/service/SaveRecruitmentAreaService.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/CodePersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/entity/CodeEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/mapper/CodeMapper.java
Labels: 기능 추가

#450 🔗 :: (#449) 내 모집의뢰 조회 시 jobcode가 제대로 안뜸
  jobis-application/src/main/java/team/retum/jobis/domain/code/model/Code.java
  jobis-application/src/main/java/team/retum/jobis/domain/code/service/GetKeywordsService.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/RecruitAreaResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/service/GetRecruitmentDetailService.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/service/SaveRecruitmentAreaService.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/QueryMyRecruitmentUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/QueryRecruitmentDetailUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/StudentQueryRecruitmentsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/CodePersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/entity/CodeEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/mapper/CodeMapper.java
Labels: 버그 수정

#462 🔗 :: (#461) 기업 비밀번호 설정 변경 기능 수정
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/RegisterCompanyWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/presentation/dto/request/UpdateForgottenPasswordWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/presentation/dto/request/UpdatePasswordWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/presentation/dto/request/LoginWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/util/RegexProperty.java
Labels: 기능 수정

#467 🔗 :: (#466) 모집의뢰 조회 필터 에러
  jobis-application/src/main/java/team/retum/jobis/common/util/StringUtil.java
Labels: 버그 수정

#474 🔗 :: (#473) 학생 취업상태 조회 버그
  jobis-application/src/main/java/team/retum/jobis/domain/application/dto/response/QueryEmploymentCountResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/spi/QueryApplicationPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/spi/vo/TotalApplicationCountVO.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryEmploymentCountUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/auth/usecase/SendAuthCodeUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/student/spi/QueryStudentPort.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/repository/ApplicationJpaRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/repository/vo/QueryTotalApplicationCountVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/StudentPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/repository/StudentJpaRepository.java
Labels: 버그 수정

#476 🔗 :: (#475) 페이지 개수 문제
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/StudentQueryRecruitmentsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
Labels: 버그 수정
