Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2023-04, with the labels that each got.

#167 🔗 :: (#166) 모집의뢰 상태 다중변경
  src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentJpaRepository.java
  src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/RecruitController.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/request/ChangeRecruitmentRequest.java
  src/main/java/team/returm/jobis/domain/recruitment/service/TeacherChangeRecruitmentStatusService.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
Labels: 기능 수정

#171 🔗 :: (#170) 컬럼 수 증가
  src/main/java/team/returm/jobis/domain/company/domain/Company.java
  src/main/java/team/returm/jobis/domain/company/presentation/dto/request/RegisterCompanyRequest.java
Labels: 리팩토링

#177 🔗 :: (#173) 사업자등록증 칼럼 추가
  src/main/java/team/returm/jobis/domain/company/domain/Company.java
  src/main/java/team/returm/jobis/domain/company/presentation/dto/request/RegisterCompanyRequest.java
  src/main/java/team/returm/jobis/domain/company/service/RegisterCompanyService.java
Labels: 기능 추가

#176 🔗 :: (#172) RefreshToken 만료시간 반환
  src/main/java/team/returm/jobis/domain/company/service/RegisterCompanyService.java
  src/main/java/team/returm/jobis/domain/student/service/StudentSignUpService.java
  src/main/java/team/returm/jobis/domain/user/presentation/UserController.java
  src/main/java/team/returm/jobis/domain/user/presentation/dto/response/TokenResponse.java
  src/main/java/team/returm/jobis/domain/user/presentation/dto/response/UserAuthResponse.java
  src/main/java/team/returm/jobis/domain/user/service/LoginService.java
  src/main/java/team/returm/jobis/domain/user/service/TokenReissueService.java
  src/main/java/team/returm/jobis/global/security/jwt/JwtTokenProvider.java
  src/main/java/team/returm/jobis/global/security/jwt/TokenType.java
Labels: 기능 추가

#183 🔗 :: (#181) 전화번호 컬럼 제거
  src/main/java/team/returm/jobis/domain/student/domain/Student.java
  src/main/java/team/returm/jobis/domain/student/presentation/dto/request/StudentSignUpRequest.java
  src/main/java/team/returm/jobis/domain/student/service/StudentSignUpService.java
Labels: 리팩토링

#159 🔗 :: (#155) 학생 모집의뢰서 기술코드 검색 필터 추가
  src/main/java/team/returm/jobis/domain/code/domain/repository/CodeRepository.java
  src/main/java/team/returm/jobis/domain/code/service/QueryJobCodesService.java
  src/main/java/team/returm/jobis/domain/code/service/QueryTechCodesService.java
  src/main/java/team/returm/jobis/domain/company/domain/repository/CompanyRepository.java
  src/main/java/team/returm/jobis/domain/company/presentation/CompanyController.java
  src/main/java/team/returm/jobis/domain/company/service/StudentQueryCompaniesService.java
  src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/RecruitmentController.java
  src/main/java/team/returm/jobis/domain/recruitment/service/StudentQueryRecruitmentsService.java
  src/main/java/team/returm/jobis/domain/recruitment/service/TeacherQueryRecruitmentsService.java
Labels: 기능 추가

#185 🔗 :: (#184) 토큰 재발급 api위치 변경
  src/main/java/team/returm/jobis/domain/auth/presentation/AuthController.java
  src/main/java/team/returm/jobis/domain/auth/service/TokenReissueService.java
  src/main/java/team/returm/jobis/domain/user/presentation/UserController.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
Labels: 리팩토링

#186 🔗 :: (#180) 기업구분 변경 api
  src/main/java/team/returm/jobis/domain/company/domain/Company.java
  src/main/java/team/returm/jobis/domain/company/domain/repository/CompanyJpaRepository.java
  src/main/java/team/returm/jobis/domain/company/domain/repository/CompanyRepository.java
  src/main/java/team/returm/jobis/domain/company/presentation/CompanyController.java
  src/main/java/team/returm/jobis/domain/company/presentation/dto/request/UpdateCompanyTypeRequest.java
  src/main/java/team/returm/jobis/domain/company/service/UpdateCompanyTypeService.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#199 🔗 :: (#198) 선생님 모집의뢰 리스트 조회 수정
  src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
  src/main/java/team/returm/jobis/domain/recruitment/service/TeacherQueryRecruitmentsService.java
Labels: 기능 수정

#204 🔗 :: (#203) 지원서 조회시 company_id querystring 추가
  src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/team/returm/jobis/domain/application/presentation/ApplicationController.java
  src/main/java/team/returm/jobis/domain/application/presentation/dto/request/QueryApplicationsRequest.java
  src/main/java/team/returm/jobis/domain/application/service/QueryCompanyApplicationsService.java
  src/main/java/team/returm/jobis/domain/application/service/QueryStudentApplicationsService.java
  src/main/java/team/returm/jobis/domain/application/service/TeacherQueryApplicationsService.java
Labels: 기능 추가

#201 🔗 :: (#191) 취업관리 회사리스트 조회 api
  src/main/java/team/returm/jobis/domain/application/domain/Application.java
  src/main/java/team/returm/jobis/domain/application/domain/enums/ApplicationStatus.java
  src/main/java/team/returm/jobis/domain/company/domain/Company.java
  src/main/java/team/returm/jobis/domain/company/domain/repository/CompanyRepository.java
  src/main/java/team/returm/jobis/domain/company/domain/repository/vo/TeacherQueryEmployCompaniesVO.java
  src/main/java/team/returm/jobis/domain/company/presentation/CompanyController.java
  src/main/java/team/returm/jobis/domain/company/presentation/dto/response/TeacherQueryEmployCompaniesResponse.java
  src/main/java/team/returm/jobis/domain/company/service/TeacherQueryEmployCompaniesService.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#200 🔗 :: (#197) 모집의뢰서 조회시 지원자와 지원요청을 따로 반환
  src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/team/returm/jobis/domain/application/service/ChangeApplicationsStatusService.java
  src/main/java/team/returm/jobis/domain/application/service/CreateApplicationService.java
  src/main/java/team/returm/jobis/domain/application/service/DeleteApplicationService.java
  src/main/java/team/returm/jobis/domain/company/service/RegisterCompanyService.java
  src/main/java/team/returm/jobis/domain/recruitment/domain/Recruitment.java
  src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
  src/main/java/team/returm/jobis/domain/recruitment/domain/repository/vo/QueryRecruitmentsVO.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/response/TeacherQueryRecruitmentsResponse.java
  src/main/java/team/returm/jobis/domain/recruitment/service/TeacherQueryRecruitmentsService.java
Labels: 기능 추가

#188 🔗 :: (#164) 코드 테이블 재설계
  src/main/java/team/returm/jobis/domain/code/domain/Code.java
  src/main/java/team/returm/jobis/domain/code/domain/repository/CodeJpaRepository.java
  src/main/java/team/returm/jobis/domain/code/domain/repository/CodeRepository.java
  src/main/java/team/returm/jobis/domain/code/facade/CodeFacade.java
  src/main/java/team/returm/jobis/domain/code/service/QueryJobCodesService.java
  src/main/java/team/returm/jobis/domain/code/service/QueryTechCodesService.java
  src/main/java/team/returm/jobis/domain/recruitment/service/ApplyRecruitmentService.java
  src/main/java/team/returm/jobis/domain/recruitment/service/CreateRecruitAreaService.java
  src/main/java/team/returm/jobis/domain/recruitment/service/UpdateRecruitAreaService.java
Labels: 기능 수정

#206 🔗 :: (#202) 현장실습생, 근로계약생 조회 api
  src/main/java/team/returm/jobis/domain/acceptance/domain/Acceptance.java
  src/main/java/team/returm/jobis/domain/acceptance/domain/repository/AcceptanceJpaRepository.java
  src/main/java/team/returm/jobis/domain/acceptance/domain/repository/AcceptanceRepository.java
  src/main/java/team/returm/jobis/domain/acceptance/presentation/AcceptanceController.java
  src/main/java/team/returm/jobis/domain/acceptance/presentation/dto/response/.gitkeep
  src/main/java/team/returm/jobis/domain/acceptance/presentation/dto/response/TeacherQueryFieldTraineesAndContractWorkersResponse.java
  src/main/java/team/returm/jobis/domain/acceptance/service/.gitkeep
  src/main/java/team/returm/jobis/domain/acceptance/service/TeacherQueryFieldTraineesAndContractWorkersService.java
  src/main/java/team/returm/jobis/domain/application/domain/Application.java
  src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/team/returm/jobis/domain/application/domain/repository/vo/QueryFieldTraineesVO.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#209 🔗 :: (#208) 현장실습생 전환 api
  src/main/java/team/returm/jobis/domain/acceptance/presentation/AcceptanceController.java
  src/main/java/team/returm/jobis/domain/acceptance/presentation/dto/request/RegisterFieldTraineeRequest.java
  src/main/java/team/returm/jobis/domain/acceptance/service/RegisterFieldTraineeService.java
  src/main/java/team/returm/jobis/domain/application/domain/Application.java
  src/main/java/team/returm/jobis/domain/application/exception/ApplicationStatusCannotChangeException.java
  src/main/java/team/returm/jobis/domain/application/presentation/ApplicationController.java
  src/main/java/team/returm/jobis/domain/application/service/TeacherQueryApplicationsService.java
  src/main/java/team/returm/jobis/global/error/exception/ErrorCode.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#215 🔗 :: (#210) 근로계약 전환 api
  src/main/java/team/returm/jobis/domain/acceptance/domain/Acceptance.java
  src/main/java/team/returm/jobis/domain/acceptance/domain/repository/AcceptanceRepository.java
  src/main/java/team/returm/jobis/domain/acceptance/domain/repository/vo/ApplicationDetailVO.java
  src/main/java/team/returm/jobis/domain/acceptance/presentation/AcceptanceController.java
  src/main/java/team/returm/jobis/domain/acceptance/presentation/dto/request/.gitkeep
  src/main/java/team/returm/jobis/domain/acceptance/presentation/dto/request/RegisterEmploymentContractRequest.java
  src/main/java/team/returm/jobis/domain/acceptance/presentation/dto/response/TeacherQueryFieldTraineesAndContractWorkersResponse.java
  src/main/java/team/returm/jobis/domain/acceptance/service/RegisterEmploymentContractService.java
  src/main/java/team/returm/jobis/domain/acceptance/service/TeacherQueryFieldTraineesAndContractWorkersService.java
  src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationJpaRepository.java
  src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/team/returm/jobis/domain/application/domain/repository/vo/QueryFieldTraineesVO.java
  src/main/java/team/returm/jobis/domain/application/service/ChangeApplicationsStatusService.java
  src/main/java/team/returm/jobis/domain/recruitment/service/ApplyRecruitmentService.java
  src/main/java/team/returm/jobis/domain/recruitment/service/UpdateRecruitmentService.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
  src/main/java/team/returm/jobis/global/util/StringUtil.java
Labels: 기능 추가

#212 🔗 :: (#208) 현장실습 날짜 변경 api
  src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationJpaRepository.java
  src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/team/returm/jobis/domain/application/exception/FieldTrainDateCannotChangeException.java
  src/main/java/team/returm/jobis/domain/application/exception/InvalidDateException.java
  src/main/java/team/returm/jobis/domain/application/presentation/ApplicationController.java
  src/main/java/team/returm/jobis/domain/application/presentation/dto/request/ChangeFieldTrainDateRequest.java
  src/main/java/team/returm/jobis/domain/application/service/ChangeFieldTrainDateService.java
  src/main/java/team/returm/jobis/global/error/exception/ErrorCode.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#214 🔗 :: (#213) 근로계약 날짜 변경 api
  src/main/java/team/returm/jobis/domain/acceptance/domain/repository/AcceptanceJpaRepository.java
  src/main/java/team/returm/jobis/domain/acceptance/domain/repository/AcceptanceRepository.java
  src/main/java/team/returm/jobis/domain/acceptance/presentation/AcceptanceController.java
  src/main/java/team/returm/jobis/domain/acceptance/presentation/dto/request/ChangeContractDateRequest.java
  src/main/java/team/returm/jobis/domain/acceptance/presentation/dto/response/TeacherQueryFieldTraineesAndContractWorkersResponse.java
  src/main/java/team/returm/jobis/domain/acceptance/service/ChangeContractDateService.java
  src/main/java/team/returm/jobis/domain/acceptance/service/TeacherQueryFieldTraineesAndContractWorkersService.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#219 🔗 :: (#218) 선생님 지원서 조회시 querystring 변경
  src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/team/returm/jobis/domain/application/presentation/ApplicationController.java
  src/main/java/team/returm/jobis/domain/application/service/QueryCompanyApplicationsService.java
  src/main/java/team/returm/jobis/domain/application/service/QueryStudentApplicationsService.java
  src/main/java/team/returm/jobis/domain/application/service/TeacherQueryApplicationsService.java
  src/main/java/team/returm/jobis/global/util/StringUtil.java
Labels: 기능 수정
