Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2023-08, with the labels that each got.

#367 🔗 :: (#366) toEntity함수 버그 수정
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/mapper/CompanyMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/entity/StudentEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/mapper/StudentMapper.java
Labels: 버그 수정

#371 🔗 :: (#370) review mysql로 이전
  jobis-application/src/main/java/team/retum/jobis/domain/application/spi/QueryApplicationPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/DeleteApplicationUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/RejectApplicationUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/vo/TeacherCompaniesVO.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/TeacherQueryCompaniesUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/dto/CreateReviewRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/dto/QueryReviewDetailResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/dto/QueryReviewsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/model/QnA.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/model/Review.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/spi/CommandReviewPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/spi/QueryReviewPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/spi/vo/QnAVO.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/spi/vo/ReviewVO.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/CreateReviewUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/DeleteReviewUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/QueryReviewDetailUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/QueryReviewsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/repository/vo/TeacherQueryCompaniesVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/ReviewPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/entity/QnAElementEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/entity/QnAEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/entity/ReviewEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/mapper/QnAElementMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/mapper/QnAMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/mapper/ReviewMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/repository/QnAJpaRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/repository/ReviewJpaRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/repository/ReviewRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/repository/vo/QueryQnAVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/repository/vo/QueryReviewVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/presentation/ReviewWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/presentation/dto/CreateReviewWebRequest.java
Labels: 기능 수정

#373 🔗 :: (#372) Address 분리
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/request/UpdateCompanyDetailsRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/CompanyMyPageResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/QueryCompanyDetailsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/model/Company.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/vo/CompanyDetailsVO.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/CompanyMyPageUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/QueryCompanyDetailsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/RegisterCompanyUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/UpdateCompanyDetailsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/type/Address.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/mapper/CompanyMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/repository/vo/QueryCompanyDetailsVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/UpdateCompanyDetailsWebRequest.java
Labels: 기능 수정

#375 🔗 :: (#374) 기업 내 모집의뢰서 조회 id반환
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/QueryRecruitmentDetailResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/vo/RecruitmentDetailVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/vo/QueryRecruitmentDetailVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/mapper/StudentMapper.java
Labels: 기능 수정

#377 🔗 :: (#376) 후기 작성 가능기업조회 api
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/QueryReviewAvailableCompaniesResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/QueryCompanyPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/QueryReviewAvailableCompaniesUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/repository/vo/QueryReviewAvailableCompanyVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#379 🔗 :: (#378) 기업저장 버그 수정
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/RegisterCompanyUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/UpdateCompanyDetailsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/RegisterCompanyWebRequest.java
Labels: 버그 수정

#381 🔗 :: (#380) firebase 세팅
  jobis-infrastructure/build.gradle
  jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FirebaseConfig.java
  jobis-infrastructure/src/main/resources/application.yml
Labels: 프로젝트 세팅

#386 🔗 :: (#385) 모집분야관련 리펙토링
  jobis-application/src/main/java/team/retum/jobis/common/annotation/Service.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/service/SaveRecruitmentAreaService.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ApplyRecruitmentUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/CreateRecruitAreaUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/UpdateRecruitAreaUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/annotation/config/ComponentScanConfig.java
Labels: 리팩토링

#387 🔗 :: (#382) 후기 작성 applicationId 제거
  jobis-application/src/main/java/team/retum/jobis/domain/application/spi/QueryApplicationPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/dto/CreateReviewRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/spi/QueryReviewPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/CreateReviewUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/ReviewPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/repository/ReviewJpaRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/presentation/dto/CreateReviewWebRequest.java
Labels: 기능 수정

#391 🔗 :: (#390) 기업 상세 조회 시 주소 분리
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/QueryCompanyDetailsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/QueryCompanyDetailsUseCase.java
Labels: 기능 수정

#393 🔗 :: (#389) ThreadLocal적용
  jobis-application/src/main/java/team/retum/jobis/common/spi/SecurityPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/acceptance/usecase/RegisterFieldTraineeUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/model/Application.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/CreateApplicationUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/DeleteApplicationUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryCompanyApplicationsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryStudentApplicationsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/bookmark/usecase/BookmarkUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/code/usecase/.gitkeep
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/CompanyMyPageUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/UpdateCompanyDetailsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/CreateReviewUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/student/usecase/CheckStudentPasswordUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/student/usecase/StudentMyPageUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/student/usecase/UpdateStudentPasswordUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/student/usecase/UpdateStudentProfileUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/user/usecase/LoginUseCase.java
  jobis-infrastructure/build.gradle
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/teacher/persistence/entity/TeacherEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/teacher/persistence/mapper/TeacherMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/persistence/UserPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/aop/ThreadLocalAspect.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/CurrentUserHolder.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/company/CompanyDetailsService.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/student/StudentDetailsService.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/teacher/TeacherDetailsService.java
Labels: 기능 수정, 리팩토링

#395 🔗 :: (#394) 모집의뢰 조회 버그
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/RegisterCompanyUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/mapper/CompanyMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/persistence/entity/UserEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/persistence/mapper/UserMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/config/MysqlDialectConfig.java
Labels: 버그 수정

#402 🔗 :: (#401) 기업 정보 수정할 때 식별키 받아와 수정
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/CompanyMyPageResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/model/Company.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/CompanyMyPageUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/UpdateCompanyDetailsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
Labels: 기능 수정
