Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2023-03, with the labels that each got.

#124 🧩 :: (#119) 기업지원내역 상세조회 api
  src/main/java/com/example/jobis/domain/application/controller/ApplicationController.java
  src/main/java/com/example/jobis/domain/application/controller/dto/request/QueryApplicationsRequest.java
  src/main/java/com/example/jobis/domain/application/controller/dto/response/QueryCompanyApplicationsResponse.java
  src/main/java/com/example/jobis/domain/application/controller/dto/response/StudentApplicationListResponse.java
  src/main/java/com/example/jobis/domain/application/controller/dto/response/StudentApplicationsResponse.java
  src/main/java/com/example/jobis/domain/application/controller/dto/response/TeacherQueryApplicationsResponse.java
  src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationRepository.java
  src/main/java/com/example/jobis/domain/application/domain/repository/vo/QueryApplicationVO.java
  src/main/java/com/example/jobis/domain/application/service/QueryCompanyApplicationsService.java
  src/main/java/com/example/jobis/domain/application/service/QueryStudentApplicationService.java
  src/main/java/com/example/jobis/domain/application/service/QueryStudentApplicationsService.java
  src/main/java/com/example/jobis/domain/application/service/TeacherQueryApplicationsService.java
  src/main/java/com/example/jobis/domain/company/controller/CompanyController.java
  src/main/java/com/example/jobis/domain/student/controller/StudentController.java
  src/main/java/com/example/jobis/domain/student/controller/dto/request/StudentSignUpRequest.java
  src/main/java/com/example/jobis/domain/student/domain/Student.java
  src/main/java/com/example/jobis/domain/student/service/StudentSignUpService.java
  src/main/java/com/example/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#133 🔗 :: codeowners
  .github/CODEOWNERS
Labels: 프로젝트 세팅

#138 🔗 :: 모집의뢰 상태변경 스케줄러
  src/main/java/team/returm/jobis/JobisApplication.java
  src/main/java/team/returm/jobis/domain/company/domain/type/Manager.java
  src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
  src/main/java/team/returm/jobis/domain/recruitment/domain/repository/vo/QueryRecruitmentsVO.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/RecruitController.java
  src/main/java/team/returm/jobis/domain/recruitment/service/ChangeRecruitmentStatusSchedulerService.java
  src/main/java/team/returm/jobis/domain/recruitment/service/TeacherChangeRecruitmentStatusService.java
  src/main/java/team/returm/jobis/domain/recruitment/service/TeacherQueryRecruitmentsService.java
  src/main/java/team/returm/jobis/global/scheduler/RecruitmentScheduler.java
Labels: 기능 추가

#140 🔗 :: (#139) 기술코드 조회 이슈
  src/main/java/team/returm/jobis/domain/code/domain/repository/CodeJpaRepository.java
  src/main/java/team/returm/jobis/domain/code/facade/CodeFacade.java
  src/main/java/team/returm/jobis/domain/code/presentation/CodeController.java
  src/main/java/team/returm/jobis/domain/code/service/QueryJobCodesService.java
  src/main/java/team/returm/jobis/domain/code/service/QueryTechCodesService.java
Labels: 버그 수정

#142 🔗 :: (#141) pr template
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feat.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 프로젝트 세팅

#144 🔗 :: (#113) 내 모집의뢰서 조회 api
  src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
  src/main/java/team/returm/jobis/domain/recruitment/facade/RecruitFacade.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/RecruitController.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/response/QueryMyRecruitmentResponse.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/response/RecruitAreaResponse.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/response/StudentRecruitDetailsResponse.java
  src/main/java/team/returm/jobis/domain/recruitment/service/QueryMyRecruitmentService.java
  src/main/java/team/returm/jobis/domain/recruitment/service/StudentQueryRecruitmentDetailService.java
  src/main/java/team/returm/jobis/domain/user/facade/UserFacade.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#146 🔗 :: (#145) cascade 적용
  src/main/java/team/returm/jobis/domain/company/domain/Company.java
  src/main/java/team/returm/jobis/domain/company/service/RegisterCompanyService.java
  src/main/java/team/returm/jobis/domain/recruitment/domain/Recruitment.java
  src/main/java/team/returm/jobis/domain/student/domain/Student.java
  src/main/java/team/returm/jobis/domain/student/service/StudentSignUpService.java
  src/main/java/team/returm/jobis/domain/teacher/domain/Teacher.java
  src/main/resources/application.yml
Labels: 리팩토링

#143 🔗 :: (#63) 모집의뢰, 회사 상세조회에 각각 아이디칼럼 추가
  src/main/java/team/returm/jobis/domain/company/domain/repository/CompanyRepository.java
  src/main/java/team/returm/jobis/domain/company/presentation/CompanyController.java
  src/main/java/team/returm/jobis/domain/company/presentation/dto/response/CompanyDetailsResponse.java
  src/main/java/team/returm/jobis/domain/company/presentation/dto/response/QueryCompanyDetailsResponse.java
  src/main/java/team/returm/jobis/domain/company/service/QueryCompanyDetailsService.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/dto/response/StudentRecruitDetailsResponse.java
  src/main/java/team/returm/jobis/domain/recruitment/service/StudentQueryRecruitmentDetailService.java
Labels: 기능 추가

#153 🔗 :: 모집의뢰 삭제 api
  src/main/java/team/returm/jobis/domain/code/domain/RecruitAreaCode.java
  src/main/java/team/returm/jobis/domain/recruitment/domain/Recruitment.java
  src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
  src/main/java/team/returm/jobis/domain/recruitment/exception/RecruitmentCannotDeleteException.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/RecruitController.java
  src/main/java/team/returm/jobis/domain/recruitment/service/CreateRecruitAreaService.java
  src/main/java/team/returm/jobis/domain/recruitment/service/DeleteRecruitmentService.java
  src/main/java/team/returm/jobis/domain/recruitment/service/UpdateRecruitAreaService.java
  src/main/java/team/returm/jobis/domain/recruitment/service/UpdateRecruitmentService.java
  src/main/java/team/returm/jobis/global/error/exception/ErrorCode.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#149 🔗 :: (#148) codeType조건 추가
  src/main/java/team/returm/jobis/domain/code/domain/repository/CodeJpaRepository.java
  src/main/java/team/returm/jobis/domain/code/service/QueryTechCodesService.java
Labels: 버그 수정

#157 🔗 :: (#156) 모집분야 삭제 api
  src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
  src/main/java/team/returm/jobis/domain/recruitment/exception/RecruitNotFoundException.java
  src/main/java/team/returm/jobis/domain/recruitment/facade/RecruitFacade.java
  src/main/java/team/returm/jobis/domain/recruitment/presentation/RecruitController.java
  src/main/java/team/returm/jobis/domain/recruitment/service/DeleteRecruitAreaService.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#161 🔗 :: (#160) 이메일 중복 컬럼 제거
  src/main/java/team/returm/jobis/domain/student/domain/Student.java
  src/main/java/team/returm/jobis/domain/student/domain/repository/StudentJpaRepository.java
  src/main/java/team/returm/jobis/domain/student/facade/StudentFacade.java
  src/main/java/team/returm/jobis/domain/student/presentation/dto/request/StudentSignUpRequest.java
  src/main/java/team/returm/jobis/domain/student/service/SendSignUpAuthCodeService.java
  src/main/java/team/returm/jobis/domain/student/service/StudentSignUpService.java
  src/main/java/team/returm/jobis/domain/user/domain/User.java
  src/main/java/team/returm/jobis/domain/user/domain/repository/UserJpaRepository.java
  src/main/java/team/returm/jobis/domain/user/facade/UserFacade.java
  src/main/java/team/returm/jobis/global/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: 프로젝트 세팅

#165 🔗 :: (#162) 이메일 템플릿 설정
  build.gradle
  src/main/java/team/returm/jobis/domain/auth/domain/AuthCode.java
  src/main/java/team/returm/jobis/domain/auth/exception/AuthCodeNotFoundException.java
  src/main/java/team/returm/jobis/domain/auth/facade/AuthCodeFacade.java
  src/main/java/team/returm/jobis/domain/auth/presentation/dto/request/SendAuthCodeRequest.java
  src/main/java/team/returm/jobis/domain/auth/service/SendAuthCodeService.java
  src/main/java/team/returm/jobis/domain/auth/service/VerifyAuthCodeService.java
  src/main/java/team/returm/jobis/domain/student/service/StudentSignUpService.java
  src/main/java/team/returm/jobis/domain/student/service/UpdateStudentPasswordService.java
  src/main/java/team/returm/jobis/domain/user/domain/repository/UserRepository.java
  src/main/java/team/returm/jobis/domain/user/facade/UserFacade.java
  src/main/java/team/returm/jobis/global/error/exception/ErrorCode.java
  src/main/java/team/returm/jobis/global/util/StringUtil.java
  src/main/java/team/returm/jobis/global/util/jms/JmsUtil.java
  src/main/resources/templates/signup-template.html
Labels: 기능 추가, 리팩토링
