Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2024-08, with the labels that each got.

#690 🔗 :: (#677) 취업 현황 조회 api
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryEmploymentRateUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/EmploymentRatesResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/QueryCompanyPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/vo/CompanyVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/repository/vo/QueryCompanyVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#695 🔗 :: (#694) bucket env 추가
  .github/workflows/build.yml
Labels: 프로젝트 세팅

#696 🔗 :: (#691) yml 파일 분리
  .github/workflows/build.yml
  jobis-infrastructure/src/main/resources/application-dev.yml
  jobis-infrastructure/src/main/resources/application-local.yml
  jobis-infrastructure/src/main/resources/application-prod.yml
  jobis-infrastructure/src/main/resources/application.yml
Labels: 기능 추가

#698 🧩 :: (#697) 알림 전체 구독/해제 api
  jobis-application/src/main/java/team/retum/jobis/domain/notification/usecase/subscribe/SubscribeAllTopicsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/usecase/subscribe/UnsubscribeAllTopicsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/presentation/NotificationWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#701 🔗 :: (#700) 엔드포인트 수정
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/presentation/NotificationWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
Labels: 리팩토링

#707 🔗 :: (#705) queryport 메서드명 통일
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryEmploymentRateUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/auth/usecase/CompanySignInUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/banner/spi/QueryBannerPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/banner/usecase/QueryBannersUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/bookmark/spi/QueryBookmarkPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/bookmark/usecase/BookmarkUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/bookmark/usecase/QueryStudentBookmarksUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/QueryCompanyPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/CheckCompanyExistsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/ExportCompanyHistoryUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/QueryCompanyDetailsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/QueryReviewAvailableCompaniesUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/RegisterCompanyUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/StudentQueryCompaniesUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/TeacherQueryCompaniesUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/TeacherQueryEmployCompaniesUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/UpdateCompanyDetailsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/UpdateCompanyTypeUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/UpdateMouUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/interest/spi/QueryInterestPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/interest/usecase/QueryMyInterestsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/spi/QueryNoticePort.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/DeleteNoticeUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/QueryNoticeDetailUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/QueryNoticesUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/UpdateNoticeUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/exception/error/NotificationErrorCode.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/spi/QueryNotificationPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/usecase/QueryNotificationsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/usecase/ReadNotificationUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ApplyRecruitmentUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/CreateReviewUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/QueryReviewsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/student/spi/QueryStudentPort.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/Interest/persistence/InterestPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/persistence/BannerPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/bookmark/persistence/BookmarkPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/NoticePersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/NotificationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/StudentPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/recruitment/RecruitmentEventHandler.java
Labels: 리팩토링

#710 🔗 :: (#709) flyway 스크립트 작성
  jobis-infrastructure/src/main/resources/db/migration/V5__create_interest.sql
Labels: 기능 수정

#711 🔗 :: (#702) 토픽 조회 api
  jobis-application/src/main/java/team/retum/jobis/domain/notice/spi/vo/TopicVO.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/dto/response/QueryTopicsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/model/TopicSubscription.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/spi/QueryTopicSubscriptionPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/spi/TopicSubscriptionPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/usecase/QueryTopicsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/TopicSubscriptionPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/entity/TopicSubscriptionEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/entity/TopicSubscriptionId.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/mapper/TopicSubscriptionMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/repository/TopicSubscriptionJpaRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/presentation/NotificationWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
Labels: 기능 추가
