Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2024-05, with the labels that each got.

#656 🔗 :: (#655) 병특 필터링 추가
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/RecruitmentFilter.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/StudentQueryRecruitmentsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
Labels: 기능 추가

#659 🔗 :: (#658) 기술스택 필터링 추가
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
Labels: 기능 추가

#662 🔗 :: (#661) 모집의뢰서, 기업, 지원서 총 개수
  jobis-application/src/main/java/team/retum/jobis/domain/application/dto/response/ApplicationCountResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/spi/QueryApplicationPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/TeacherQueryApplicationsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/CompanyCountResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/QueryCompanyPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/TeacherQueryCompaniesUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/RecruitmentCountResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#664 🔗 :: (#663) 어드민 지원서 삭제
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/TeacherDeleteApplicationUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#668 🔗 :: (#667) 로 -> 으로
  jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java
Labels: 리팩토링

#670 🔗 :: (#669) 학생 회사 리스트 조회 버그
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
Labels: 버그 수정

#671 🔗 :: (#665) 리뷰 작성 예외처리 수정
  jobis-application/src/main/java/team/retum/jobis/domain/application/model/ApplicationStatus.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/CreateReviewUseCase.java
Labels: 기능 추가

#675 🔗 :: (#674) 지원서 엔드포인트 변경
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
Labels: 리팩토링

#673 🔗 :: 기업 리스트 최근 의뢰년도로 수정
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
Labels: 기능 수정
