Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2024-09, with the labels that each got.

#718 🔗 :: (#717) 겨울인턴 메서드명 및 로직 수정
  jobis-application/src/main/java/team/retum/jobis/domain/intern/model/WinterIntern.java
  jobis-application/src/main/java/team/retum/jobis/domain/intern/spi/QueryWinterInternPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/intern/usecase/QueryIsWinterInternUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/intern/usecase/ToggleWinterInternUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/intern/persistence/WinterInternPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/intern/persistence/entity/WinterInternEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/intern/presentation/WinterInternWebAdapter.java
Labels: 기능 수정, 리팩토링

#721 🔗 :: (#719) 스케줄러에 주석처리
  jobis-infrastructure/src/main/java/team/retum/jobis/global/scheduler/BannerScheduler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/scheduler/InterestedRecruitmentScheduler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/scheduler/RecruitmentScheduler.java
Labels: 리팩토링

#720 🔗 :: (#713) 메서드 이름 통일
  jobis-application/src/main/java/team/retum/jobis/domain/application/spi/CommandApplicationPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/ReapplyUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/bookmark/spi/CommandBookmarkPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/bookmark/usecase/BookmarkUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/CommandCompanyPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/RegisterCompanyUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/UpdateCompanyDetailsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/UpdateCompanyTypeUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/UpdateMouUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/interest/spi/CommandInterestPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/interest/usecase/ToggleInterestUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/spi/CommandNoticePort.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/CreateNoticeUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/DeleteNoticeUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/UpdateNoticeUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/spi/CommandNotificationPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/spi/CommandTopicSubscriptionPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/usecase/ReadNotificationUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/usecase/subscribe/SubscribeAllTopicsByToggleUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/usecase/subscribe/SubscribeTopicByToggleUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/spi/CommandReviewPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/CreateReviewUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/Interest/persistence/InterestPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/bookmark/persistence/BookmarkPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/NoticePersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/NotificationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/TopicSubscriptionPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/ReviewPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/notice/NoticeEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/recruitment/RecruitmentEventHandler.java
Labels: 리팩토링

#723 🔗 :: (#722) 알림 기본값 넣어줌
  jobis-application/src/main/java/team/retum/jobis/domain/notification/spi/CommandTopicSubscriptionPort.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/TopicSubscriptionPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/repository/TopicSubscriptionJpaRepository.java
Labels: 기능 수정

#727 🔗 :: (#726) 겨울인턴 여부 조회 학생 권한 추가
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
Labels: 기능 수정

#725 🔗 :: (#724) 관심사 토글 조회 로직 변경
  jobis-application/src/main/java/team/retum/jobis/domain/interest/spi/QueryInterestPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/interest/usecase/ToggleInterestUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/Interest/persistence/InterestPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/Interest/persistence/repository/InterestJpaRepository.java
Labels: 리팩토링
