Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2024-04, with the labels that each got.

#618 🔗 :: (#617) topic 구독 방식 공지사항 알림
  jobis-application/src/main/java/team/retum/jobis/domain/notice/event/NoticePostedEvent.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/exception/FailedToSubscriptionException.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/exception/FailedToUnsubscriptionException.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/exception/error/NotificationErrorCode.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/model/Topic.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/spi/CommandNotificationPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/usecase/subscribe/SubscribeTopicUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/usecase/subscribe/UnsubscribeTopicUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/user/model/User.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/NotificationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/presentation/NotificationWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/persistence/UserPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/persistence/entity/UserEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/persistence/repository/UserJpaRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/notice/NoticeEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
  jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FCMUtil.java
  jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FirebaseConfig.java
Labels: 기능 추가

#623 🔗 :: (#622) template 변경
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feat.md
  .github/ISSUE_TEMPLATE/feat.yml
  .github/ISSUE_TEMPLATE/fix.yml
  .github/ISSUE_TEMPLATE/refactor.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 프로젝트 세팅

#625 🔗 :: (#624) bug 리펙토링
  jobis-application/src/main/java/team/retum/jobis/domain/bug/spi/CommandBugReportPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/bug/spi/PublishBugReportEventPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/bug/spi/QueryBugReportPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/bug/usecase/CreateBugReportUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/bug/usecase/QueryBugReportDetailsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/bug/usecase/QueryBugReportsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/bug/persistence/BugReportPersistenceAdapter.java
Labels: 리팩토링

#621 🔗 :: (#620) Recruitment 리펙토링
  jobis-application/src/main/java/team/retum/jobis/common/util/FileUtil.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/CompanyQueryApplicationsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/CreateApplicationUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/bookmark/usecase/BookmarkUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/QueryCompanyPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/checker/RecruitmentChecker.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/QueryRecruitmentDetailResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/CommandRecruitAreaPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/CommandRecruitmentPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitAreaPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/RecruitAreaPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ApplyRecruitmentUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ChangeRecruitmentStatusSchedulerUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/CreateRecruitAreaUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/DeleteRecruitAreaUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/DeleteRecruitmentUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/QueryMyRecruitmentUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/QueryMyRecruitmentsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/QueryRecruitmentDetailUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/StudentQueryRecruitmentsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherChangeRecruitmentStatusUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/UpdateRecruitAreaUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/UpdateRecruitmentUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitAreaPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/annotation/config/ComponentScanConfig.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/util/LogUtil.java
  jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FCMUtil.java
Labels: 리팩토링

#631 🔗 :: (#628) 공지사항 작성 알림 송신
  jobis-application/src/main/java/team/retum/jobis/domain/notice/model/Notice.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/spi/CommandNoticePort.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/CreateNoticeUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/NoticePersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/entity/NoticeEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/mapper/NoticeMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/notice/NoticeEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FCMUtil.java
Labels: 기능 수정

#635 🔗 :: (#634) application attachment 구조 변경
  jobis-application/src/main/java/team/retum/jobis/domain/application/spi/CommandApplicationPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/ReapplyUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/entity/ApplicationAttachmentEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/entity/ApplicationEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/mapper/ApplicationMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/repository/ApplicationJpaRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/entity/NoticeEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FCMUtil.java
  jobis-infrastructure/src/main/resources/application.yml
  jobis-infrastructure/src/main/resources/db/migration/V2__application_attchament.sql
Labels: 버그 수정

#632 🔗 :: (#614) 모집의뢰서 엑셀 출력
  jobis-application/src/main/java/team/retum/jobis/common/spi/WriteFilePort.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/ExportRecruitmentHistoryResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ExportRecruitmentHistoryUseCase.java
  jobis-infrastructure/build.gradle
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
  jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/paser/ExcelAdapter.java
Labels: 기능 추가

#627 🔗 :: (#626) code, file 패키지 리펙토링
  jobis-application/src/main/java/team/retum/jobis/domain/code/service/GetKeywordsService.java
  jobis-application/src/main/java/team/retum/jobis/domain/code/spi/CommandCodePort.java
  jobis-application/src/main/java/team/retum/jobis/domain/code/spi/QueryCodePort.java
  jobis-application/src/main/java/team/retum/jobis/domain/code/usecase/CreateCodeUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/code/usecase/QueryCodesUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/RegisterCompanyUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/TeacherQueryCompaniesUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/file/spi/FilePort.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/CodePersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/s3/S3Adapter.java
Labels: 리팩토링

#638 🔗 :: (#636) 지원서 updated_at 추가
  jobis-application/src/main/java/team/retum/jobis/domain/application/model/Application.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/entity/ApplicationEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/mapper/ApplicationMapper.java
  jobis-infrastructure/src/main/resources/db/migration/V3__application_updated_at.sql
Labels: 기능 추가

#640 🔗 :: (#639) Mapper 리펙토링
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/ExportRecruitmentHistoryResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ApplyRecruitmentUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ExportRecruitmentHistoryUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/acceptance/persistence/mapper/AcceptanceMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/bookmark/persistence/mapper/BookmarkMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/bug/persistence/mapper/BugReportMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/entity/RecruitAreaCodeId.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/mapper/CodeMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/repository/CodeJpaRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/mapper/NoticeMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/mapper/NotificationMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitAreaPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/entity/RecruitAreaEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/mapper/RecruitAreaMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/mapper/RecruitmentMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/ApplyRecruitmentWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/UpdateRecruitmentWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/mapper/QnAMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/mapper/ReviewMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/repository/ReviewJpaRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/mapper/PortfolioMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/mapper/StudentMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/teacher/persistence/mapper/TeacherMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/persistence/repository/UserJpaRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/util/RegexProperty.java
Labels: 리팩토링, 버그 수정

#651 🔗 :: (#633) 배너 엔티티 detailId 추가
  jobis-application/src/main/java/team/retum/jobis/domain/banner/dto/request/CreateBannerRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/banner/model/Banner.java
  jobis-application/src/main/java/team/retum/jobis/domain/banner/spi/vo/BannerVO.java
  jobis-application/src/main/java/team/retum/jobis/domain/banner/spi/vo/TeacherBannersVO.java
  jobis-application/src/main/java/team/retum/jobis/domain/banner/usecase/CreateBannerUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/persistence/BannerPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/persistence/entity/BannerEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/persistence/mapper/BannerMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/persistence/repository/vo/QueryBannerVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/persistence/repository/vo/QueryTeacherBannersVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/presentation/dto/CreateBannerWebRequest.java
Labels: 기능 수정

#653 🔗 :: (#652) 기업 조회 paging optional 처리
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/CompanyFilter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
  jobis-infrastructure/src/main/resources/application.yml
  jobis-infrastructure/src/main/resources/db/migration/V4__add_detail_id.sql
Labels: 기능 수정
