Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2024-10, with the labels that each got.

#729 🔗 :: (#728) 기업 이메일 정규식 확인 코드 추가
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/auth/presentation/dto/request/SendAuthCodeWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/RegisterCompanyWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/UpdateCompanyDetailsWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/presentation/dto/request/StudentSignUpWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/presentation/dto/request/UpdateForgottenPasswordWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/util/RegexProperty.java
Labels: 기능 추가

#733 🔗 :: (#732) 기본 이미지 변경
  jobis-infrastructure/src/main/java/team/retum/jobis/global/util/ImageProperty.java
Labels: 기능 추가

#735 🔗: (#734) 회사별 모집의뢰서 확인 로직 추가
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/CheckRecruitmentExistsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/RecruitmentJpaRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#737 🔗 :: (#736) 사업자 등록증 not null로 수정
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/RegisterCompanyWebRequest.java
Labels: 기능 수정

#739 🔗 :: (#738) 500 에러 -> 400 bad request
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/RegisterCompanyWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/RecruitAreaWebRequest.java
Labels: 버그 수정

#741 🔗 :: (#740) 전화번호 validation 추가
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/RegisterCompanyWebRequest.java
Labels: 버그 수정

#743 🔗 :: (#742) 파일 업로드 시 특수문자 방지
  jobis-infrastructure/src/main/java/team/retum/jobis/global/util/RegexProperty.java
Labels: 기능 수정

#747 🔗 :: (#745) 최소 성적 최댓값 설정
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/ApplyRecruitmentWebRequest.java
Labels: 버그 수정

#748 🔗 :: (#746) 파일명 정규식 수정
  jobis-infrastructure/src/main/java/team/retum/jobis/global/util/RegexProperty.java
Labels: 기능 수정, 버그 수정

#751 🔗 :: (#744) 모집의뢰서 수정 validation 추가
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/UpdateRecruitmentWebRequest.java
Labels: 버그 수정

#750 🔗 :: (#749) 회원가입시 topic 자동 구독
  jobis-application/src/main/java/team/retum/jobis/domain/notification/spi/CommandNotificationPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/student/usecase/StudentSignUpUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/NotificationPersistenceAdapter.java
Labels: 기능 추가

#753 🔗 :: (#752) 모집의뢰서 지원 비활성화
  jobis-application/src/main/java/team/retum/jobis/domain/application/spi/QueryApplicationPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/QueryRecruitmentDetailUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/repository/ApplicationJpaRepository.java
Labels: 기능 수정

#760 🔗 :: (#759) 모집의뢰 상세 조회 버그 해결
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/repository/ApplicationJpaRepository.java
Labels: 버그 수정

#761 🔗 :: (#756) 기업등록 시 user 생성
  jobis-application/src/main/java/team/retum/jobis/domain/company/model/Company.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/RegisterCompanyUseCase.java
Labels: 기능 수정

#758 🔗 :: (#757) 토픽 구독 예외처리 추가
  jobis-application/src/main/java/team/retum/jobis/domain/notification/exception/DeviceTokenNotFoundException.java
  jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FCMUtil.java
Labels: 기능 추가

#764 🔗 :: (#762) 대표번호 validiation 수정
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/UpdateCompanyDetailsWebRequest.java
Labels: 기능 수정

#767 🔗 :: (#766) 토픽 구독 예외처리 추가
  jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FCMUtil.java
Labels: 버그 수정

#769 🔗 :: (#768) 필요없는 필드 삭제
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/request/RegisterCompanyRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/request/UpdateCompanyDetailsRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/CompanyMyPageResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/QueryCompanyDetailsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/model/Company.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/model/ManagerInfo.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/vo/CompanyDetailsVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/type/Manager.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/mapper/CompanyMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/repository/vo/QueryCompanyDetailsVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/RegisterCompanyWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/UpdateCompanyDetailsWebRequest.java
  jobis-infrastructure/src/main/resources/db/migration/V10__delete_column_in_company.sql
Labels: 기능 수정

#771 🔗 :: (#770) 컬럼 길이 줄이기
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/UpdateCompanyDetailsWebRequest.java
  jobis-infrastructure/src/main/resources/db/migration/V11_modify_company_column_length.sql
Labels: 기능 수정

#776 🔗 :: (#775) deviceToken 삭제 API 추가
  jobis-application/src/main/java/team/retum/jobis/domain/user/model/User.java
  jobis-application/src/main/java/team/retum/jobis/domain/user/usecase/RemoveDeviceTokenUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/presentation/UserWebAdapter.java
Labels: 기능 추가

#780 🔗 :: (#779) 서브 주소 삭제
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/request/RegisterCompanyRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/request/UpdateCompanyDetailsRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/CompanyMyPageResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/QueryCompanyDetailsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/model/AddressInfo.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/model/Company.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/vo/CompanyDetailsVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/type/Address.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/mapper/CompanyMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/repository/vo/QueryCompanyDetailsVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/RegisterCompanyWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/UpdateCompanyDetailsWebRequest.java
  jobis-infrastructure/src/main/resources/db/migration/V11__modify_company_column_length.sql
  jobis-infrastructure/src/main/resources/db/migration/V13__delete_column_in_company.sql
Labels: 기능 수정

#785 🔗 :: (#774) isConvertible 추가
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/request/ApplyRecruitmentRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/request/UpdateRecruitmentRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/QueryRecruitmentDetailResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/TeacherQueryRecruitmentsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/model/Recruitment.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/vo/RecruitmentDetailVO.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/vo/TeacherRecruitmentVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/entity/RecruitmentEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/mapper/RecruitmentMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/vo/QueryRecruitmentDetailVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/vo/QueryTeacherRecruitmentsVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/ApplyRecruitmentWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/UpdateRecruitmentWebRequest.java
  jobis-infrastructure/src/main/resources/db/migration/V13__add_hire_convertible.sql
Labels: 기능 추가

#784 🔗 :: (#783) 반별 학생 수 조회 로직 추가
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryEmploymentRateUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/EmploymentRatesResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/student/spi/QueryStudentPort.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/StudentPersistenceAdapter.java
Labels: 기능 추가, 기능 수정

#789 🔗 :: (#788) 컬럼명 수정
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/request/RegisterCompanyRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/request/UpdateCompanyDetailsRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/CompanyMyPageResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/QueryCompanyDetailsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/model/Company.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/vo/CompanyDetailsVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/mapper/CompanyMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/repository/vo/QueryCompanyDetailsVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/RegisterCompanyWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/UpdateCompanyDetailsWebRequest.java
  jobis-infrastructure/src/main/resources/db/migration/V16__modify_column_name_in_company.sql
Labels: 기능 수정

#791 🔗 :: (#790) 컬럼명 통일
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/CompanyMyPageResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/QueryCompanyDetailsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/model/Company.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/vo/CompanyDetailsVO.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/request/ApplyRecruitmentRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/QueryRecruitmentDetailResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/TeacherQueryRecruitmentsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/model/Recruitment.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/vo/RecruitmentDetailVO.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/vo/TeacherRecruitmentVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/mapper/CompanyMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/repository/vo/QueryCompanyDetailsVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/entity/RecruitmentEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/mapper/RecruitmentMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/vo/QueryRecruitmentDetailVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/vo/QueryTeacherRecruitmentsVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/ApplyRecruitmentWebRequest.java
  jobis-infrastructure/src/main/resources/db/migration/V17__rename_column_in_company.sql
Labels: 리팩토링

#793 🔗 :: (#792) isHireConvertible 제거
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/TeacherQueryRecruitmentsResponse.java
Labels: 기능 수정

#795 🔗 :: (#794) 대표 번호 수정
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/request/RegisterCompanyRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/request/UpdateCompanyDetailsRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/CompanyMyPageResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/QueryCompanyDetailsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/model/Company.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/model/ManagerInfo.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/vo/CompanyDetailsVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/type/Manager.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/mapper/CompanyMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/repository/vo/QueryCompanyDetailsVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/RegisterCompanyWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/UpdateCompanyDetailsWebRequest.java
  jobis-infrastructure/src/main/resources/db/migration/V18__modify_column_in_company.sql
Labels: 기능 수정

#797 🔗 :: (#796) 컬럼 수정
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/request/ApplyRecruitmentRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/request/UpdateRecruitmentRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/QueryMyRecruitmentResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/QueryRecruitmentDetailResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/model/Recruitment.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/vo/RecruitmentDetailVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/entity/RecruitmentEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/mapper/RecruitmentMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/vo/QueryRecruitmentDetailVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/ApplyRecruitmentWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/UpdateRecruitmentWebRequest.java
  jobis-infrastructure/src/main/resources/db/migration/V19__modify_column_name_in_recruitment.sql
Labels: 기능 수정

#799 🔗 :: (#798) 겨울인턴 여부 추가
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/QueryRecruitmentDetailResponse.java
Labels: 기능 추가

#801 🔗 :: (#800) 총개수 조회 api 추가
  jobis-application/src/main/java/team/retum/jobis/domain/application/dto/ApplicationFilter.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/dto/response/ApplicationCountResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/spi/QueryApplicationPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/TeacherQueryApplicationsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/CompanyCountResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/QueryCompanyPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/TeacherQueryCompaniesUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/RecruitmentCountResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
Labels: 기능 추가

#803 🔗 :: (#802) 총개수 버그 수정
  jobis-application/src/main/java/team/retum/jobis/domain/application/dto/response/ApplicationCountResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/TeacherQueryApplicationsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/RecruitmentCountResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
Labels: 버그 수정

#806 🔗 :: (#805) 기업 로그인 시 비밀번호 제거
  jobis-application/src/main/java/team/retum/jobis/domain/auth/usecase/CompanySignInUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/RegisterCompanyUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/auth/presentation/AuthWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/auth/presentation/dto/request/CompanySignInWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/persistence/entity/UserEntity.java
  jobis-infrastructure/src/main/resources/db/migration/V20__modify_column_in_user.sql
Labels: 기능 수정
