Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2024-11, with the labels that each got.

#812 🔗 :: (#811) 체험형 모집의뢰서 등록 시 알림
  jobis-application/src/main/java/team/retum/jobis/domain/notification/model/Topic.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/event/WinterInternRegisteredEvent.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ApplyRecruitmentUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/recruitment/RecruitmentEventHandler.java
Labels: 기능 추가

#813 🔗 :: (#810) military null 처리
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/request/ApplyRecruitmentRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/request/UpdateRecruitmentRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/StudentQueryRecruitmentsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/model/Recruitment.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/vo/StudentRecruitmentVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/entity/RecruitmentEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/mapper/RecruitmentMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/vo/QueryStudentRecruitmentsVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/ApplyRecruitmentWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/UpdateRecruitmentWebRequest.java
  jobis-infrastructure/src/main/resources/db/migration/V22__modify_column_in_recruitment.sql
Labels: 기능 추가

#817 🔗 :: (#816) 모집의뢰서, 회사 컬럼 수정
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/request/RegisterCompanyRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/request/UpdateCompanyDetailsRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/CompanyMyPageResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/QueryCompanyDetailsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/model/Company.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/model/ManagerInfo.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/vo/CompanyDetailsVO.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/request/ApplyRecruitmentRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/request/UpdateRecruitmentRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/QueryRecruitmentDetailResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/model/Recruitment.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/vo/RecruitmentDetailVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/type/Manager.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/mapper/CompanyMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/repository/vo/QueryCompanyDetailsVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/RegisterCompanyWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/UpdateCompanyDetailsWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/entity/RecruitmentEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/mapper/RecruitmentMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/vo/QueryRecruitmentDetailVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/ApplyRecruitmentWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/UpdateRecruitmentWebRequest.java
  jobis-infrastructure/src/main/resources/db/migration/V23__update_column_in_recruitment_and_company.sql
Labels: 기능 추가, 기능 수정

#821 🔗 :: (#820) 알림 타입 및 로직 수정
  jobis-application/src/main/java/team/retum/jobis/domain/intern/event/WinterInternRegisteredEvent.java
  jobis-application/src/main/java/team/retum/jobis/domain/notification/model/Topic.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ApplyRecruitmentUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ChangeRecruitmentStatusSchedulerUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/intern/WinterInternEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/notice/NoticeEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/recruitment/RecruitmentEventHandler.java
Labels: 기능 추가, 기능 수정

#824 🔗 :: (823) 지원서 필터링 수정
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
Labels: 버그 수정

#827 🔗 :: (#826) 대표번호 추가
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/QueryCompanyDetailsResponse.java
Labels: 기능 수정

#829 🔗 :: (#828) phonw -> phone
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/QueryCompanyDetailsResponse.java
Labels: 버그 수정

#831 🔗 :: (#830) 겨울인턴 여부로 확인
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/CheckRecruitmentExistsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/RecruitmentJpaRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
Labels: 기능 수정

#835 🔗 :: (#834) response 변경
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/RecruitmentExistsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/QueryRecruitmentPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/CheckRecruitmentExistsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/RecruitmentJpaRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
Labels: 기능 수정

#837 🔗 :: (836) 디바이스 토큰 플랫폼 타입 설정
  jobis-application/src/main/java/team/retum/jobis/domain/student/usecase/StudentSignUpUseCase.java
Labels: 버그 수정

#839 🔗 :: (#838) 모집중인 상태만 체크
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
Labels: 기능 수정

#843 🔗 :: (#842) 채용인원 쿼리 변경
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
Labels: 기능 수정

#845 🔗 :: (844) 기본 이미지 변경
  jobis-infrastructure/src/main/java/team/retum/jobis/global/util/ImageProperty.java
Labels: 버그 수정

#847 🔗 :: (#846) 기본생성자 추가
  jobis-application/src/main/java/team/retum/jobis/domain/acceptance/dto/response/TeacherQueryFieldTraineesAndContractWorkersResponse.java
Labels: 버그 수정

#849 🔗 :: (848) 지원서 버그 픽스
  jobis-application/src/main/java/team/retum/jobis/domain/application/model/ApplicationStatus.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/dto/request/CreateApplicationWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/file/presentation/dto/CreatePreSignedUrlWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/util/RegexProperty.java
Labels: 버그 수정

#851 🔗 :: (#850) 공지 파일 nullable로 변경
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/presentation/dto/CreateNoticeWebRequest.java
Labels: 기능 수정

#853 ⚙️ :: (8452) 공지 첨부물 nullable
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/TeacherQueryCompaniesUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/file/model/FileType.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/dto/response/QueryNoticeDetailResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/CreateNoticeUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/mapper/NoticeMapper.java
Labels: 버그 수정

#859 🔗 :: (858) 지원서 페이징 제거
  jobis-application/src/main/java/team/retum/jobis/domain/application/dto/ApplicationFilter.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/TeacherQueryApplicationsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java
Labels: 버그 수정

#860 🔗 :: (#857) 반려시 알림 추가
  jobis-application/src/main/java/team/retum/jobis/domain/application/event/SingleApplicationStatusChangedEvent.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/RejectApplicationUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java
Labels: 기능 추가

#862 🔗 :: (809) 모집의뢰서 상태 변경 스케줄러 수정
  jobis-application/src/main/java/team/retum/jobis/domain/intern/event/WinterInternRegisteredEvent.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ApplyRecruitmentUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ChangeRecruitmentStatusSchedulerUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/presentation/NotificationWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/intern/WinterInternEventHandler.java
Labels: 버그 수정

#861 🔗 :: (#857) 알림 메세지 설정
  jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationMessage.java
Labels: 기능 추가
