Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2024-03, with the labels that each got.

#546 🔗 :: (#545) company detail 조회 예외처리
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/QueryCompanyPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/QueryCompanyDetailsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
Labels: 버그 수정

#549 🔗 :: (#548) 공지사항 삭제 api
  jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/DeleteNoticeUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/presentation/NoticeWebAdapter.java
Labels: 기능 추가

#552 🔗 :: (#550) 배너 리스트 선생님 조회
  jobis-application/src/main/java/team/retum/jobis/domain/banner/dto/TeacherQueryBannersResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/banner/spi/QueryBannerPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/banner/spi/vo/TeacherBannersVO.java
  jobis-application/src/main/java/team/retum/jobis/domain/banner/usecase/TeacherQueryBannersUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/persistence/BannerPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/persistence/repository/vo/QueryTeacherBannersVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/presentation/BannerWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#557 🔗 :: (#554) 기업 로그인 API
  jobis-application/src/main/java/team/retum/jobis/common/spi/SecurityPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/auth/usecase/CompanySignInUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/request/RegisterCompanyRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/CheckCompanyExistsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/RegisterCompanyResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/CheckCompanyExistsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/RegisterCompanyUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ApplyRecruitmentUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/auth/presentation/AuthWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/auth/presentation/dto/.gitkeep
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/auth/presentation/dto/request/CompanySignInWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/entity/CompanyEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/mapper/CompanyMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/RegisterCompanyWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/company/CompanyDetailsService.java
  jobis-infrastructure/src/main/resources/application.yml
Labels: 기능 추가, 기능 수정

#569 🔗 :: (#568) DB 마이그레이션 툴 적용
  jobis-infrastructure/build.gradle
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/entity/RecruitmentEntity.java
  jobis-infrastructure/src/main/resources/application.yml
  jobis-infrastructure/src/main/resources/db/migration/V1__modify_is_public.sql
Labels: 프로젝트 세팅

#573 🔗 :: (#572) 기업 회원가입 버그
  jobis-application/src/main/java/team/retum/jobis/domain/company/model/Company.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/mapper/CompanyMapper.java
Labels: 버그 수정

#571 🔗 :: (#570) 공지사항 상세 조회
  jobis-application/src/main/java/team/retum/jobis/domain/notice/dto/response/AttachmentResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/dto/response/QueryNoticeDetailResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/model/NoticeAttachment.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/QueryNoticeDetailUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/mapper/NoticeMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/presentation/NoticeWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#575 🔗 :: (#574) 버그 제보 시 이미지가 null이면 NPE 발생
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/bug/persistence/entity/BugAttachmentEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/bug/presentation/dto/request/CreateBugReportWebRequest.java
Labels: 버그 수정

#578 🔗 :: (#577) 기업 내 정보 조회 api 수정
  jobis-application/build.gradle
  jobis-application/src/main/java/team/retum/jobis/common/util/StringUtil.java
  jobis-application/src/main/java/team/retum/jobis/domain/auth/usecase/SendAuthCodeUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/CompanyMyPageResponse.java
  jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FirebaseConfig.java
Labels: 기능 수정

#580 🔗 :: (#579) 기업정보 수정 API변경
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/request/UpdateCompanyDetailsRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/model/Company.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/UpdateCompanyDetailsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/UpdateCompanyDetailsWebRequest.java
Labels: 기능 수정

#559 🔗 :: (#558) 공지사항 리스트 조회
  jobis-application/src/main/java/team/retum/jobis/domain/notice/dto/response/QueryNoticesResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/spi/QueryNoticePort.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/spi/vo/NoticeVO.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/QueryNoticesUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/NoticePersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/persistence/repository/vo/QueryNoticeVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/presentation/NoticeWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#583 🔗 :: (#582) 공지사항 상세 조회 권한 부여
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#585 🔗 :: (#582) 공지사항 상세 조회 권한 부여
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notice/presentation/NoticeWebAdapter.java
Labels: 기능 추가

#587 🔗 :: (#581) 기업 모집의뢰 수정 권한 부여
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/request/ApplyRecruitmentRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/QueryMyRecruitmentResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/QueryRecruitmentDetailResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/model/Recruitment.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/service/CheckRecruitmentPermissionService.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/spi/vo/RecruitmentDetailVO.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ChangeRecruitmentStatusSchedulerUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/CreateRecruitAreaUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/DeleteRecruitAreaUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/DeleteRecruitmentUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/StudentQueryRecruitmentsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherQueryRecruitmentsUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/UpdateRecruitAreaUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/UpdateRecruitmentUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/RegisterCompanyWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/UpdateCompanyDetailsWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/entity/RecruitmentEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/mapper/RecruitmentMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/vo/QueryRecruitmentDetailVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/ApplyRecruitmentWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/RecruitAreaWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/UpdateRecruitmentWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/presentation/dto/request/StudentSignUpWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
  jobis-infrastructure/src/main/resources/application.yml
  jobis-infrastructure/src/main/resources/db/migration/V2__modify_recruitment.sql
Labels: 기능 수정

#591 🔗 :: (#590) 모집분야 중복문제
  jobis-application/src/main/java/team/retum/jobis/domain/code/model/Code.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/model/RecruitArea.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/UpdateRecruitAreaUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/UpdateRecruitmentWebRequest.java
Labels: 버그 수정

#597 🔗 :: (#596) 모집의뢰서 아이디 반환
  jobis-application/src/main/java/team/retum/jobis/domain/code/model/CodeResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/RecruitAreaResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/QueryRecruitmentDetailUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/repository/vo/QueryRecruitAreaVO.java
Labels: 기능 추가
