Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2024-06, with the labels that each got.

#679 🔗 :: (#678) 진행중 상태일때 알림 안가게 변경
  jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java
Labels: 기능 추가

#676 🔗 :: (#666) 기업 엑셀 출력 추가
  jobis-application/src/main/java/team/retum/jobis/common/spi/WriteFilePort.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/ExportCompanyHistoryResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/ExportCompanyHistoryUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
  jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/paser/ExcelAdapter.java
Labels: 기능 추가

#681 🔗 :: (#680) 합격 통지 문구 변경
  jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java
Labels: 리팩토링

#684 🔗 :: (#683) 코드 리팩토링
  jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java
Labels: 리팩토링

#685 🔗 :: (#682) offset 수정
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/RecruitmentFilter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
Labels: 버그 수정

#687 🔗 :: (#686) 기업 엑셀 널 처리 추가
  jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/paser/ExcelAdapter.java
Labels: 버그 수정
