Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2024-01, with the labels that each got.

#494 🔗 :: (#493) 캐시 적용
  jobis-application/src/main/java/team/retum/jobis/common/dto/response/TotalPageCountResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/dto/response/AttachmentResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/dto/response/QueryEmploymentCountResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/dto/response/QueryPassedApplicationStudentsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/dto/response/QueryRejectionReasonResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/dto/response/TeacherQueryApplicationsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/code/dto/response/CodesResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/QueryCompanyDetailsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/StudentQueryCompaniesResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/TeacherQueryCompaniesResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/dto/response/TeacherQueryEmployCompaniesResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/vo/StudentCompaniesVO.java
  jobis-application/src/main/java/team/retum/jobis/domain/company/spi/vo/TeacherEmployCompaniesVO.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/QueryRecruitmentDetailResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/RecruitAreaResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/StudentQueryRecruitmentsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/dto/response/TeacherQueryRecruitmentsResponse.java
  jobis-infrastructure/build.gradle
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/acceptance/presentation/AcceptanceWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/presentation/CodeWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/repository/vo/QueryTeacherEmployCompaniesVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/repository/vo/StudentQueryCompaniesVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/presentation/StudentWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/config/cache/CacheConfig.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/config/cache/CacheName.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/config/cache/CustomKeyGenerator.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/company/CompanyDetails.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/company/CompanyDetailsService.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/student/StudentDetails.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/student/StudentDetailsService.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/teacher/TeacherDetails.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/auth/teacher/TeacherDetailsService.java
  jobis-infrastructure/src/main/resources/application.yml
Labels: 기능 추가

#504 🔗 :: (#503) 자잘한 리팩토링
  jobis-application/src/main/java/team/retum/jobis/domain/acceptance/usecase/ChangeContractDateUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/model/Application.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/spi/QueryApplicationPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/ChangeApplicationsStatusUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/ChangeFieldTrainDateUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/DeleteApplicationUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryRejectionReasonUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/model/Recruitment.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/DeleteRecruitmentUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/acceptance/presentation/dto/request/ChangeContractDateWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/dto/request/ChangeFieldTrainDateWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/web/WebSecurityConfig.java
Labels: 리팩토링

#509 🔗 :: (#508) 북마크할 때 모집의뢰서 변경 안되는 문제 발생
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/bookmark/presentation/BookmarkWebAdapter.java
Labels: 버그 수정

#513 🔗 :: (#512) 오타수정
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/util/RegexProperty.java
Labels: 버그 수정
