Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2025-08, with the labels that each got.

#995 🔗 :: (#994) 후기 작성 가능 기업 지원서 상태 추가
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
Labels: 기능 추가

#1007 🔗 :: (#1002) 리뷰 상세 조회 api
  jobis-application/src/main/java/team/retum/jobis/domain/review/dto/response/QnAResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/dto/response/QueryReviewDetailResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/spi/QueryReviewPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/spi/vo/QnAVO.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/spi/vo/ReviewDetailVO.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/spi/vo/ReviewVO.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/QueryReviewDetailUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/QueryReviewsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/ReviewPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/repository/ReviewJpaRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/repository/vo/QueryQnAVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/repository/vo/QueryReviewDetailVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/repository/vo/QueryReviewVO.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/presentation/ReviewWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#1013 🔗 :: (#991) 새로운 리뷰 작성 기능 추가
  jobis-application/src/main/java/team/retum/jobis/domain/review/dto/QuestionElement.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/dto/request/CreateReviewRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/dto/response/QueryReviewOptionsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/spi/CommandQuestionPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/spi/QueryQuestionPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/CreateReviewUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/QueryReviewOptionsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/QuestionPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/persistence/entity/ReviewEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/presentation/ReviewWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/presentation/dto/CreateReviewWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/presentation/dto/request/CreateReviewWebRequest.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
Labels: 기능 추가

#1016 🔗 :: (#1015) 리뷰옵션 조회 api 수정
  jobis-application/src/main/java/team/retum/jobis/domain/review/dto/QnAElement.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/dto/response/QueryReviewQuestionsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/review/usecase/QueryReviewQuestionsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/review/presentation/ReviewWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/security/SecurityConfig.java
Labels: 기능 수정

#1021 🔗 :: (#1020) 지원서 서류 탈락 상태 추가
  jobis-application/src/main/java/team/retum/jobis/domain/application/model/ApplicationStatus.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/CreateNonSchoolContactPassApplicationsUseCase.java
Labels: 기능 추가

#1023 🔗 :: (#1022) flyway 이름 중복 오류 수정
  jobis-infrastructure/src/main/resources/db/migration/V32__create_view_log.sql
Labels: 버그 수정
