Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2025-05, with the labels that each got.

#944 🔗 :: (#942) 관심 분야 조회 시 학생 이름 추가
  jobis-application/src/main/java/team/retum/jobis/domain/interest/dto/response/StudentQueryInterestsResponse.java
  jobis-application/src/main/java/team/retum/jobis/domain/interest/usecase/QueryMyInterestsUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/Interest/presentation/InterestWebAdapter.java
Labels: 기능 추가

#946 🔗 :: (#945) 관심분야 잘못된 요청에 대한 예외 처리 추가
  jobis-application/src/main/java/team/retum/jobis/domain/code/spi/QueryCodePort.java
  jobis-application/src/main/java/team/retum/jobis/domain/interest/dto/request/ToggleInterestRequest.java
  jobis-application/src/main/java/team/retum/jobis/domain/interest/exception/InvalidCodesException.java
  jobis-application/src/main/java/team/retum/jobis/domain/interest/exception/error/InterestErrorCode.java
  jobis-application/src/main/java/team/retum/jobis/domain/interest/spi/QueryInterestPort.java
  jobis-application/src/main/java/team/retum/jobis/domain/interest/usecase/ToggleInterestUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/Interest/persistence/InterestPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/Interest/presentation/InterestWebAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/code/persistence/CodePersistenceAdapter.java
Labels: 버그 수정

#943 🔗 :: (#935) 필터링 조건 수정
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
Labels: 기능 수정

#947 🔗 :: (#941) 모집의뢰서 스케줄러 수정
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/model/Recruitment.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/recruitment/RecruitmentEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/scheduler/RecruitmentScheduler.java
Labels: 버그 수정

#951 🔗 :: (#935) 모집의뢰서 조회 필터링 적용 오류 수정
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
Labels: 버그 수정

#954 🔗:: 953 null parse error
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
Labels: 버그 수정

#956 🔗 :: (#955) 공백 문자 파싱 오류 수정
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
Labels: 버그 수정

#958 🔗 :: (#956) null 문자 파싱 오류 수정
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
Labels: 버그 수정

#961 🔗 :: (#960) 레디스 역직렬화 오류 수정
  jobis-application/src/main/java/team/retum/jobis/domain/acceptance/dto/response/TeacherQueryFieldTraineesAndContractWorkersResponse.java
Labels: 버그 수정

#965 🔗 :: (#964) 패키지 이름 변경
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/interest/persistence/InterestPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/interest/persistence/entity/InterestEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/interest/persistence/mapper/InterestMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/interest/persistence/repository/InterestJpaRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/interest/presentation/InterestWebAdapter.java
Labels: 리팩토링

#962 🔗 :: p6spy 의존성 추가
  jobis-infrastructure/build.gradle
  jobis-infrastructure/src/main/java/team/retum/jobis/global/formatter/P6spySqlLogFormatter.java
  jobis-infrastructure/src/main/resources/application-local.yml
  jobis-infrastructure/src/main/resources/spy.properties
Labels: 기능 추가
