Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2025-04, with the labels that each got.

#925 🔗 :: (#922) fcm 초기화
  jobis-infrastructure/src/main/java/team/retum/jobis/event/RabbitMqProducer.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/intern/WinterInternEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/notice/NoticeEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/recruitment/RecruitmentEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/config/RabbitMqConfig.java
Labels: 기능 수정

#927 🔗 :: (#926) 디바이스 토큰 컬럼 삭제
  jobis-application/src/main/java/team/retum/jobis/domain/notification/model/Notification.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/entity/NotificationEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/mapper/NotificationMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/EventPublisher.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/notice/NoticeEventHandler.java
  jobis-infrastructure/src/main/resources/application.yml
  jobis-infrastructure/src/main/resources/db/migration/V28__modify_column_in_notification.sql
Labels: 기능 수정

#929 🔗 :: (#928) fcm 전체 구독 스케줄러 추가
  jobis-application/src/main/java/team/retum/jobis/domain/notification/usecase/subscribe/SubscribeAllUserUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/user/spi/QueryUserPort.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/persistence/UserPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/persistence/repository/UserJpaRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/scheduler/FcmScheduler.java
Labels: 기능 추가

#933 🔗 :: (#919) 나의 지원서 조회 수정
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
Labels: 버그 수정

#934 🔗 :: (#931) flyway 추가
  jobis-infrastructure/src/main/resources/db/migration/V29__modify_column_in_company.sql
Labels: 버그 수정

#938 🔗 :: (#937) 취업률 조회 로직 수정
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
Labels: 버그 수정

#940 🔗 :: (#939) rabbitMQ 원상복구
  jobis-application/src/main/java/team/retum/jobis/domain/notification/model/Notification.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/persistence/ApplicationPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/entity/NotificationEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/mapper/NotificationMapper.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/repository/StudentJpaRepository.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/user/persistence/UserPersistenceAdapter.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/EventPublisher.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/RabbitMqProducer.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/intern/WinterInternEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/notice/NoticeEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/recruitment/RecruitmentEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/config/RabbitMqConfig.java
  jobis-infrastructure/src/main/resources/application.yml
  jobis-infrastructure/src/main/resources/db/migration/V30__add_column_in_notification.sql
Labels: 기능 추가
