Repository Team-return/JOBIS-DSM-BE, pull requests merged in 2025-03, with the labels that each got.

#866 🔗 :: (#863) rabbitmq로 메세지 발생
  jobis-infrastructure/build.gradle
  jobis-infrastructure/src/main/java/team/retum/jobis/event/EventPublisher.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/RabbitMqProducer.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/config/RabbitMqConfig.java
  jobis-infrastructure/src/main/resources/application.yml
Labels: 기능 수정

#883 🔗 :: (#882) WebRequest 이름 수정
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/TeacherRegisterCompanyUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/dto/request/TeacherRegisterCompanyWebRequest.java
Labels: 버그 수정

#885 🔗 :: (#884) rabbitmq 메세지 컨버터 추가
  jobis-infrastructure/src/main/java/team/retum/jobis/global/config/RabbitMqConfig.java
Labels: 버그 수정

#888 🔗 :: (#886) 라우팅 키 이름 통일
  jobis-infrastructure/src/main/java/team/retum/jobis/event/RabbitMqProducer.java
Labels: 버그 수정

#895 🔗 :: (#887) 역직렬화 컨버터 추가
  jobis-infrastructure/src/main/java/team/retum/jobis/global/config/RabbitMqConfig.java
Labels: 버그 수정

#897 🔗 :: rabbitmq 관련 코드 제거
  jobis-infrastructure/src/main/java/team/retum/jobis/event/EventPublisher.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/RabbitMqProducer.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/config/RabbitMqConfig.java
  jobis-infrastructure/src/main/resources/application.yml
Labels: 버그 수정

#900 🔗 :: (#899) rabbitmq 설정
  jobis-infrastructure/src/main/java/team/retum/jobis/event/EventPublisher.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/RabbitMqProducer.java
  jobis-infrastructure/src/main/java/team/retum/jobis/global/config/RabbitMqConfig.java
  jobis-infrastructure/src/main/resources/application.yml
Labels: 버그 수정

#902 🔗 :: (#901) 취업률 조회 쿼리 수정
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/StudentPersistenceAdapter.java
Labels: 기능 수정

#904 🔗 :: (#903) rabbitmq 메세지 형식 수정
  jobis-application/src/main/java/team/retum/jobis/domain/application/event/ApplicationsStatusChangedEvent.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/event/SingleApplicationStatusChangedEvent.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/ChangeApplicationsStatusUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/RejectApplicationUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/intern/event/WinterInternRegisteredEvent.java
  jobis-application/src/main/java/team/retum/jobis/domain/intern/event/WinterInternToggledEvent.java
  jobis-application/src/main/java/team/retum/jobis/domain/intern/usecase/ToggleWinterInternUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/event/NoticePostedEvent.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/CreateNoticeUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/event/InterestedRecruitmentEvent.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/event/RecruitmentStatusChangedEvent.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ApplyRecruitmentUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ChangeRecruitmentStatusSchedulerUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherChangeRecruitmentStatusUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/intern/WinterInternEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/notice/NoticeEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/recruitment/RecruitmentEventHandler.java
Labels: 기능 수정

#890 🔗 :: (#887) 고용인원 수 변경
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/entity/RecruitAreaEntity.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/dto/request/RecruitAreaWebRequest.java
Labels: 버그 수정

#906 🔗 :: (#905) 모집의뢰서 종료 시 추가 등록
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/TeacherRegisterCompanyUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ApplyRecruitmentUseCase.java
Labels: 버그 수정

#908 🔗 :: (#907) 전체 모집 의뢰서 조회 쿼리 수정
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/RecruitmentPersistenceAdapter.java
Labels: 버그 수정

#893 🔗 :: (#889) accountId 생성 로직 개선
  jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/TeacherRegisterCompanyUseCase.java
Labels: 기능 수정

#912 🔗 :: (#910) orphanRemoval 관계 설정
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/model/RecruitArea.java
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/persistence/entity/RecruitAreaEntity.java
Labels: 버그 수정

#913 merge: (#901) 쿼리 조건 수정
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/StudentPersistenceAdapter.java
Labels: 버그 수정

#915 🔗 :: (#914) 겨울 인턴 포함 여부 추가
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/StudentPersistenceAdapter.java
Labels: 버그 수정

#917 🔗 :: (#916) 3학년 조건 추가
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/student/persistence/StudentPersistenceAdapter.java
Labels: 버그 수정

#921 🔗 :: (#920) 알림 발송 객체 수정
  jobis-application/src/main/java/team/retum/jobis/domain/application/event/ApplicationsStatusChangedEvent.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/event/SingleApplicationStatusChangedEvent.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/ChangeApplicationsStatusUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/RejectApplicationUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/intern/event/WinterInternRegisteredEvent.java
  jobis-application/src/main/java/team/retum/jobis/domain/intern/event/WinterInternToggledEvent.java
  jobis-application/src/main/java/team/retum/jobis/domain/intern/usecase/ToggleWinterInternUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/event/NoticePostedEvent.java
  jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/CreateNoticeUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/event/InterestedRecruitmentEvent.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/event/RecruitmentStatusChangedEvent.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ApplyRecruitmentUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/ChangeRecruitmentStatusSchedulerUseCase.java
  jobis-application/src/main/java/team/retum/jobis/domain/recruitment/usecase/TeacherChangeRecruitmentStatusUseCase.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/EventPublisher.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/application/ApplicationEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/intern/WinterInternEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/notice/NoticeEventHandler.java
  jobis-infrastructure/src/main/java/team/retum/jobis/event/recruitment/RecruitmentEventHandler.java
Labels: 기능 수정

#923 🔗 :: (#922) 컬럼 최대 글자수 변경
  jobis-infrastructure/src/main/java/team/retum/jobis/domain/notification/persistence/entity/NotificationEntity.java
  jobis-infrastructure/src/main/resources/db/migration/V27__modify_column_in_notification.sql
Labels: 리팩토링
